<a href="https://colab.research.google.com/github/Sanjana6653/DataScience-Tasks/blob/main/Data__Handling_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/laptopData.csv')
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298.0,Lenovo,2 in 1 Convertible,14,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300.0,Lenovo,Notebook,14,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   object
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   Ram               1273 non-null   object
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight            1273 non-null   object
 11  Price             1273 non-null   float64
dtypes: float64(2), object(10)
memory usage: 122.3+ KB

In [4]:
df.isnull().sum()

Unnamed: 0          30
Company             30
TypeName            30
Inches              30
ScreenResolution    30
Cpu                 30
Ram                 30
Memory              30
Gpu                 30
OpSys               30
Weight              30
Price               30
dtype: int64

In [5]:
df[df["Company"].isnull()]
# handling missing  values
df.dropna(inplace = True)
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298.0,Lenovo,2 in 1 Convertible,14,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300.0,Lenovo,Notebook,14,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [6]:
#Remove unnamed column
df=df.drop("Unnamed: 0",axis=1)
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [7]:
# drop duplicates
df.drop_duplicates(inplace = True)
df.shape

(1244, 11)

In [8]:
# Handling Inches column

df["Inches"]=df["Inches"].replace("?","0")

df["Inches"]=df["Inches"].astype(float)
avg_inch = round(df["Inches"].mean())
avg_inch
df["Inches"]=df["Inches"].replace(0.0,avg_inch)
df["Inches"].unique()

array([13.3, 15.6, 15.4, 14. , 12. , 17.3, 13.5, 12.5, 13. , 18.4, 13.9,
       11.6, 25.6, 35.6, 12.3, 27.3, 24. , 33.5, 15. , 31.6, 17. , 14.1,
       11.3, 10.1])

In [9]:
df["Inches"].unique()

array([13.3, 15.6, 15.4, 14. , 12. , 17.3, 13.5, 12.5, 13. , 18.4, 13.9,
       11.6, 25.6, 35.6, 12.3, 27.3, 24. , 33.5, 15. , 31.6, 17. , 14.1,
       11.3, 10.1])

In [10]:
df["ScreenResolution"].unique()

array(['IPS Panel Retina Display 2560x1600', '1440x900',
       'Full HD 1920x1080', 'IPS Panel Retina Display 2880x1800',
       '1366x768', 'IPS Panel Full HD 1920x1080',
       'IPS Panel Retina Display 2304x1440',
       'IPS Panel Full HD / Touchscreen 1920x1080',
       'Full HD / Touchscreen 1920x1080',
       'Touchscreen / Quad HD+ 3200x1800', 'Touchscreen 2256x1504',
       'Quad HD+ / Touchscreen 3200x1800', 'IPS Panel 1366x768',
       'IPS Panel 4K Ultra HD / Touchscreen 3840x2160',
       'IPS Panel Full HD 2160x1440',
       '4K Ultra HD / Touchscreen 3840x2160', '1600x900',
       'IPS Panel 4K Ultra HD 3840x2160', '4K Ultra HD 3840x2160',
       'Touchscreen 1366x768', 'Touchscreen 2560x1440',
       'IPS Panel Full HD 1366x768', 'IPS Panel 2560x1440',
       'IPS Panel Full HD 2560x1440',
       'IPS Panel Retina Display 2736x1824', 'Touchscreen 2400x1600',
       '2560x1440', 'IPS Panel Quad HD+ 2560x1440',
       'IPS Panel Quad HD+ 3200x1800',
       'IPS Panel Quad HD+ / Touchscreen 3200x1800',
       'IPS Panel Touchscreen 1366x768', '1920x1080',
       'IPS Panel Full HD 1920x1200',
       'IPS Panel Touchscreen / 4K Ultra HD 3840x2160',
       'IPS Panel Touchscreen 2560x1440',
       'Touchscreen / Full HD 1920x1080', 'Quad HD+ 3200x1800',
       'IPS Panel Touchscreen 1920x1200',
       'Touchscreen / 4K Ultra HD 3840x2160',
       'IPS Panel Touchscreen 2400x1600'], dtype=object)

In [11]:
df["Cpu"].unique()

array(['Intel Core i5 2.3GHz', 'Intel Core i5 1.8GHz',
       'Intel Core i5 7200U 2.5GHz', 'Intel Core i7 2.7GHz',
       'Intel Core i5 3.1GHz', 'AMD A9-Series 9420 3GHz',
       'Intel Core i7 2.2GHz', 'Intel Core i7 8550U 1.8GHz',
       'Intel Core i5 8250U 1.6GHz', 'Intel Core i3 6006U 2GHz',
       'Intel Core i7 2.8GHz', 'Intel Core M m3 1.2GHz',
       'Intel Core i7 7500U 2.7GHz', 'Intel Core i7 2.9GHz',
       'Intel Core i3 7100U 2.4GHz', 'Intel Core i5 7300HQ 2.5GHz',
       'AMD E-Series E2-9000e 1.5GHz', 'Intel Core i5 1.6GHz',
       'Intel Core i7 8650U 1.9GHz', 'Intel Atom x5-Z8300 1.44GHz',
       'AMD E-Series E2-6110 1.5GHz', 'AMD A6-Series 9220 2.5GHz',
       'Intel Celeron Dual Core N3350 1.1GHz',
       'Intel Core i3 7130U 2.7GHz', 'Intel Core i7 7700HQ 2.8GHz',
       'Intel Core i5 2.0GHz', 'AMD Ryzen 1700 3GHz',
       'Intel Pentium Quad Core N4200 1.1GHz',
       'Intel Celeron Dual Core N3060 1.6GHz', 'Intel Core i5 1.3GHz',
       'AMD FX 9830P 3GHz', 'Intel Core i7 7560U 2.4GHz',
       'AMD E-Series 6110 1.5GHz', 'Intel Core i5 6200U 2.3GHz',
       'Intel Core M 6Y75 1.2GHz', 'Intel Core i5 7500U 2.7GHz',
       'Intel Core i3 6006U 2.2GHz', 'AMD A6-Series 9220 2.9GHz',
       'Intel Core i7 6920HQ 2.9GHz', 'Intel Core i5 7Y54 1.2GHz',
       'Intel Core i7 7820HK 2.9GHz', 'Intel Xeon E3-1505M V6 3GHz',
       'Intel Core i7 6500U 2.5GHz', 'AMD E-Series 9000e 1.5GHz',
       'AMD A10-Series A10-9620P 2.5GHz', 'AMD A6-Series A6-9220 2.5GHz',
       'Intel Core i5 2.9GHz', 'Intel Core i7 6600U 2.6GHz',
       'Intel Core i3 6006U 2.0GHz',
       'Intel Celeron Dual Core 3205U 1.5GHz',
       'Intel Core i7 7820HQ 2.9GHz', 'AMD A10-Series 9600P 2.4GHz',
       'Intel Core i7 7600U 2.8GHz', 'AMD A8-Series 7410 2.2GHz',
       'Intel Celeron Dual Core 3855U 1.6GHz',
       'Intel Pentium Quad Core N3710 1.6GHz',
       'AMD A12-Series 9720P 2.7GHz', 'Intel Core i5 7300U 2.6GHz',
       'AMD A12-Series 9720P 3.6GHz',
       'Intel Celeron Quad Core N3450 1.1GHz',
       'Intel Celeron Dual Core N3060 1.60GHz',
       'Intel Core i5 6440HQ 2.6GHz', 'Intel Core i7 6820HQ 2.7GHz',
       'AMD Ryzen 1600 3.2GHz', 'Intel Core i7 7Y75 1.3GHz',
       'Intel Core i5 7440HQ 2.8GHz', 'Intel Core i7 7660U 2.5GHz',
       'Intel Core i7 7700HQ 2.7GHz', 'Intel Core M m3-7Y30 2.2GHz',
       'Intel Core i5 7Y57 1.2GHz', 'Intel Core i7 6700HQ 2.6GHz',
       'Intel Core i3 6100U 2.3GHz', 'Intel Atom x5-Z8350 1.44GHz',
       'AMD A10-Series 9620P 2.5GHz', 'AMD E-Series 7110 1.8GHz',
       'Intel Celeron Dual Core N3350 2.0GHz',
       'AMD A9-Series A9-9420 3GHz', 'Intel Core i7 6820HK 2.7GHz',
       'Intel Core M 7Y30 1.0GHz', 'Intel Xeon E3-1535M v6 3.1GHz',
       'Intel Celeron Quad Core N3160 1.6GHz',
       'Intel Core i5 6300U 2.4GHz', 'Intel Core i3 6100U 2.1GHz',
       'AMD E-Series E2-9000 2.2GHz',
       'Intel Celeron Dual Core N3050 1.6GHz',
       'Intel Core M M3-6Y30 0.9GHz', 'AMD A9-Series 9420 2.9GHz',
       'Intel Core i5 6300HQ 2.3GHz', 'AMD A6-Series 7310 2GHz',
       'Intel Atom Z8350 1.92GHz', 'Intel Xeon E3-1535M v5 2.9GHz',
       'Intel Core i5 6260U 1.8GHz',
       'Intel Pentium Dual Core N4200 1.1GHz',
       'Intel Celeron Quad Core N3710 1.6GHz', 'Intel Core M 1.2GHz',
       'AMD A12-Series 9700P 2.5GHz', 'Intel Core i7 7500U 2.5GHz',
       'Intel Pentium Dual Core 4405U 2.1GHz',
       'AMD A4-Series 7210 2.2GHz', 'Intel Core i7 6560U 2.2GHz',
       'Intel Core M m7-6Y75 1.2GHz', 'AMD FX 8800P 2.1GHz',
       'Intel Core M M7-6Y75 1.2GHz', 'Intel Core i5 7200U 2.50GHz',
       'Intel Core i5 7200U 2.70GHz', 'Intel Atom X5-Z8350 1.44GHz',
       'Intel Core i5 7200U 2.7GHz', 'Intel Core M 1.1GHz',
       'Intel Atom x5-Z8550 1.44GHz',
       'Intel Pentium Dual Core 4405Y 1.5GHz',
       'Intel Pentium Quad Core N3700 1.6GHz', 'Intel Core M 6Y54 1.1GHz',
       'Intel Core i7 6500U 2.50GHz',
       'Intel Celeron Dual Core N3350 2GHz',
       'Samsung Cortex A72&A53 2.0GHz', 'AMD E-Series 9000 2.2GHz',
       'Intel Core M 6Y30 0.9GHz', 'AMD A9-Series 9410 2.9GHz'],
      dtype=object)

In [12]:
df["Ram"].unique()

array(['8GB', '16GB', '4GB', '2GB', '12GB', '64GB', '6GB', '32GB', '24GB',
       '1GB'], dtype=object)

In [13]:
# Handling memory column
df["Memory"].unique()
df["Memory"] = df["Memory"].replace("?","256GB SSD")
df["Memory"].unique()

array(['128GB SSD', '128GB Flash Storage', '256GB SSD', '512GB SSD',
       '500GB HDD', '256GB Flash Storage', '1TB HDD',
       '128GB SSD +  1TB HDD', '256GB SSD +  256GB SSD',
       '64GB Flash Storage', '32GB Flash Storage', '256GB SSD +  1TB HDD',
       '256GB SSD +  2TB HDD', '32GB SSD', '2TB HDD', '64GB SSD',
       '1.0TB Hybrid', '512GB SSD +  1TB HDD', '1TB SSD',
       '256GB SSD +  500GB HDD', '128GB SSD +  2TB HDD',
       '512GB SSD +  512GB SSD', '16GB SSD', '16GB Flash Storage',
       '512GB SSD +  256GB SSD', '512GB SSD +  2TB HDD',
       '64GB Flash Storage +  1TB HDD', '180GB SSD', '1TB HDD +  1TB HDD',
       '32GB HDD', '1TB SSD +  1TB HDD', '512GB Flash Storage',
       '128GB HDD', '240GB SSD', '8GB SSD', '508GB Hybrid', '1.0TB HDD',
       '512GB SSD +  1.0TB Hybrid', '256GB SSD +  1.0TB Hybrid'],
      dtype=object)

In [14]:
df["Gpu"].unique()

array(['Intel Iris Plus Graphics 640', 'Intel HD Graphics 6000',
       'Intel HD Graphics 620', 'AMD Radeon Pro 455',
       'Intel Iris Plus Graphics 650', 'AMD Radeon R5',
       'Intel Iris Pro Graphics', 'Nvidia GeForce MX150',
       'Intel UHD Graphics 620', 'Intel HD Graphics 520',
       'AMD Radeon Pro 555', 'AMD Radeon R5 M430',
       'Intel HD Graphics 615', 'AMD Radeon Pro 560',
       'Nvidia GeForce 940MX', 'Nvidia GeForce GTX 1050', 'AMD Radeon R2',
       'AMD Radeon 530', 'Nvidia GeForce 930MX', 'Intel HD Graphics',
       'Intel HD Graphics 500', 'Nvidia GeForce 930MX ',
       'Nvidia GeForce GTX 1060', 'Nvidia GeForce 150MX',
       'Intel Iris Graphics 540', 'AMD Radeon RX 580',
       'Nvidia GeForce 920MX', 'AMD Radeon R4 Graphics', 'AMD Radeon 520',
       'Nvidia GeForce GTX 1070', 'Nvidia GeForce GTX 1050 Ti',
       'Intel HD Graphics 400', 'Nvidia GeForce MX130', 'AMD R4 Graphics',
       'Nvidia GeForce GTX 940MX', 'AMD Radeon RX 560',
       'Nvidia GeForce 920M', 'AMD Radeon R7 M445', 'AMD Radeon RX 550',
       'Nvidia GeForce GTX 1050M', 'Intel HD Graphics 515',
       'AMD Radeon R5 M420', 'Intel HD Graphics 505',
       'Nvidia GTX 980 SLI', 'AMD R17M-M1-70', 'Nvidia GeForce GTX 1080',
       'Nvidia Quadro M1200', 'Nvidia GeForce 920MX ',
       'Nvidia GeForce GTX 950M', 'AMD FirePro W4190M ',
       'Nvidia GeForce GTX 980M', 'Intel Iris Graphics 550',
       'Nvidia GeForce 930M', 'Intel HD Graphics 630',
       'AMD Radeon R5 430', 'Nvidia GeForce GTX 940M',
       'Intel HD Graphics 510', 'Intel HD Graphics 405',
       'AMD Radeon RX 540', 'Nvidia GeForce GT 940MX',
       'AMD FirePro W5130M', 'Nvidia Quadro M2200M', 'AMD Radeon R4',
       'Nvidia Quadro M620', 'AMD Radeon R7 M460',
       'Intel HD Graphics 530', 'Nvidia GeForce GTX 965M',
       'Nvidia GeForce GTX1080', 'Nvidia GeForce GTX1050 Ti',
       'Nvidia GeForce GTX 960M', 'AMD Radeon R2 Graphics',
       'Nvidia Quadro M620M', 'Nvidia GeForce GTX 970M',
       'Nvidia GeForce GTX 960<U+039C>', 'Intel Graphics 620',
       'Nvidia GeForce GTX 960', 'AMD Radeon R5 520',
       'AMD Radeon R7 M440', 'AMD Radeon R7', 'Nvidia Quadro M520M',
       'Nvidia Quadro M2200', 'Nvidia Quadro M2000M',
       'Intel HD Graphics 540', 'Nvidia Quadro M1000M', 'AMD Radeon 540',
       'Nvidia GeForce GTX 1070M', 'Nvidia GeForce GTX1060',
       'Intel HD Graphics 5300', 'AMD Radeon R5 M420X',
       'AMD Radeon R7 Graphics', 'Nvidia GeForce 920',
       'Nvidia GeForce 940M', 'Nvidia GeForce GTX 930MX',
       'AMD Radeon R7 M465', 'AMD Radeon R3', 'Nvidia GeForce GTX 1050Ti',
       'AMD Radeon R7 M365X', 'AMD Radeon R9 M385',
       'Intel HD Graphics 620 ', 'Nvidia Quadro 3000M',
       'Nvidia GeForce GTX 980 ', 'AMD Radeon R5 M330',
       'AMD FirePro W4190M', 'AMD FirePro W6150M', 'AMD Radeon R5 M315',
       'Nvidia Quadro M500M', 'AMD Radeon R7 M360',
       'Nvidia Quadro M3000M', 'Nvidia GeForce 960M', 'ARM Mali T860 MP4'],
      dtype=object)

In [15]:
df["OpSys"].unique()

array(['macOS', 'No OS', 'Windows 10', 'Mac OS X', 'Linux',
       'Windows 10 S', 'Chrome OS', 'Windows 7', 'Android'], dtype=object)

In [16]:
df["Weight"].unique()
df["Weight"]=df["Weight"].str.strip("kg")
df["Weight"] = df["Weight"].replace("?","0")
df["Weight"] = df["Weight"].astype("float")
avg = round(df["Weight"].mean())
df["Weight"] = df["Weight"].replace(0.0,avg)
df["Weight"].unique()

array([1.370e+00, 1.340e+00, 1.860e+00, 1.830e+00, 2.100e+00, 2.040e+00,
       1.300e+00, 1.600e+00, 2.200e+00, 9.200e-01, 1.220e+00, 2.500e+00,
       1.620e+00, 1.910e+00, 2.300e+00, 1.350e+00, 1.880e+00, 1.890e+00,
       1.650e+00, 2.710e+00, 1.200e+00, 1.440e+00, 2.800e+00, 2.000e+00,
       2.650e+00, 2.770e+00, 3.200e+00, 1.490e+00, 2.400e+00, 2.130e+00,
       2.430e+00, 1.700e+00, 1.400e+00, 1.800e+00, 1.900e+00, 3.000e+00,
       1.252e+00, 2.700e+00, 2.020e+00, 1.630e+00, 1.960e+00, 1.210e+00,
       2.450e+00, 1.250e+00, 1.500e+00, 2.620e+00, 1.380e+00, 1.580e+00,
       1.850e+00, 1.230e+00, 2.160e+00, 2.360e+00, 7.200e+00, 2.050e+00,
       1.320e+00, 1.750e+00, 9.700e-01, 2.560e+00, 1.480e+00, 1.740e+00,
       1.100e+00, 1.560e+00, 2.030e+00, 1.050e+00, 5.400e+00, 4.400e+00,
       1.290e+00, 1.950e+00, 2.060e+00, 1.120e+00, 3.490e+00, 3.350e+00,
       2.230e+00, 2.900e+00, 4.420e+00, 2.690e+00, 2.370e+00, 4.700e+00,
       3.600e+00, 2.080e+00, 4.300e+00, 1.680e+00, 1.410e+00, 4.140e+00,
       2.180e+00, 2.240e+00, 2.670e+00, 4.100e+00, 2.140e+00, 1.360e+00,
       2.250e+00, 2.150e+00, 2.190e+00, 2.540e+00, 3.420e+00, 5.800e+00,
       1.280e+00, 2.330e+00, 1.450e+00, 2.790e+00, 8.230e+00, 1.260e+00,
       1.840e+00, 2.000e-04, 2.600e+00, 2.260e+00, 3.250e+00, 1.590e+00,
       1.130e+00, 1.420e+00, 1.780e+00, 1.150e+00, 1.270e+00, 1.430e+00,
       2.310e+00, 1.160e+00, 1.640e+00, 2.170e+00, 1.470e+00, 3.780e+00,
       1.790e+00, 9.100e-01, 1.990e+00, 4.330e+00, 1.930e+00, 1.870e+00,
       2.630e+00, 3.400e+00, 3.140e+00, 1.940e+00, 1.240e+00, 4.600e+00,
       4.500e+00, 8.400e+00, 2.730e+00, 1.390e+00, 2.290e+00, 2.590e+00,
       2.940e+00, 1.110e+01, 1.140e+00, 3.800e+00, 6.200e+00, 3.310e+00,
       1.090e+00, 3.210e+00, 1.190e+00, 1.980e+00, 1.170e+00, 4.360e+00,
       1.710e+00, 2.320e+00, 4.200e+00, 1.550e+00, 8.100e-01, 1.180e+00,
       2.720e+00, 1.310e+00, 3.740e+00, 1.760e+00, 1.540e+00, 2.830e+00,
       2.070e+00, 2.380e+00, 3.580e+00, 1.080e+00, 9.800e-01, 2.750e+00,
       2.990e+00, 1.110e+00, 2.090e+00, 4.000e+00, 9.900e-01, 6.900e-01,
       3.520e+00, 2.591e+00, 2.210e+00, 3.300e+00, 2.191e+00, 2.340e+00])

In [17]:
df["Price"].unique()

array([ 71378.6832,  47895.5232,  30636.    , 135195.336 ,  96095.808 ,
        21312.    , 114017.6016,  61735.536 ,  79653.6   ,  41025.6   ,
        20986.992 ,  18381.0672, 130001.6016,  26581.392 ,  67260.672 ,
        80908.344 ,  39693.6   , 152274.24  ,  26586.72  ,  52161.12  ,
        53226.72  ,  13746.24  ,  43636.32  ,  35111.52  ,  22305.1392,
        58554.72  ,  42624.    ,  69157.44  ,  47738.88  ,  13053.0672,
        10602.72  ,  23389.92  ,  99580.32  ,  53173.44  ,  13266.72  ,
        19553.76  ,  26037.4032,  46833.12  ,  20725.92  ,  79866.72  ,
        27864.9072,  36336.96  ,  75604.32  ,  69210.72  ,  34045.92  ,
        24828.48  ,  44808.48  ,  21231.5472,  58767.84  ,  20459.52  ,
        40908.384 ,  31232.2032, 130482.72  ,  22111.2   ,  31914.72  ,
        50136.48  ,  36763.2   , 105654.24  ,  23373.4032,  12201.12  ,
        29250.72  ,  50562.72  ,  58021.92  ,  50882.4   ,  46353.6   ,
        58341.6   ,  27652.32  ,  45554.4   ,  28238.4   ,  52054.56  ,
        58403.4048,  80452.8   ,  45820.8   ,  21258.72  ,  21045.6   ,
        71874.72  ,  37242.72  ,  31914.1872,  77202.72  ,  87858.72  ,
        36709.92  ,  63776.16  ,  63669.6   ,  55890.72  ,  45128.16  ,
        31962.672 ,  25840.8   ,  30742.56  ,  66546.72  ,  38308.32  ,
        18594.72  ,  34472.16  ,  59620.32  ,  71395.2   ,  22105.872 ,
        63563.04  ,  78854.4   ,  67239.36  ,  73473.12  ,  74538.72  ,
        38468.16  ,  86793.12  ,  57755.52  ,  60223.9824,  30049.92  ,
        59567.04  ,  25521.12  , 119427.12  ,  33513.12  ,  67718.88  ,
        24029.28  ,  43263.36  ,  14811.3072,  74378.88  ,  49443.84  ,
        34045.3872,  23922.72  ,  47099.52  ,  30476.16  ,  31861.44  ,
        52640.64  ,  13445.7408,  49976.64  ,  34898.4   ,  59461.5456,
        46300.32  ,  32074.56  ,  19660.32  , 107305.92  ,  18328.32  ,
        23816.16  ,  66560.5728,  47898.72  ,  26533.44  , 100699.2   ,
        57648.96  ,  32980.32  ,  70063.2   ,  21471.84  ,  42890.4   ,
        38787.84  ,  57489.12  ,  18541.44  ,  95850.72  ,  19367.8128,
        56502.9072,  45501.12  ,  40173.12  ,  16463.52  ,  26053.92  ,
        49177.44  ,  24455.52  , 149130.72  ,  43316.64  ,  98514.72  ,
        42251.04  ,  63882.72  ,  82530.72  , 127712.16  ,  41505.12  ,
        52693.92  ,  57808.8   ,  13852.8   ,  53274.672 ,  37189.44  ,
        44701.92  ,  48697.92  , 324954.72  ,  51095.52  ,  55677.6   ,
        98301.6   ,  26267.04  ,  39533.76  ,  93186.72  , 162770.4   ,
        74485.44  , 103842.72  ,  74964.96  ,  49650.5664,  31381.92  ,
        54931.68  ,  61218.72  ,  68145.12  ,  36089.208 ,  72620.64  ,
        42304.32  , 130873.7952,  44328.96  ,  45768.0528,  40972.32  ,
        47472.48  ,  67612.32  ,  21258.1872,  17582.4   ,  45767.52  ,
        20779.2   , 207259.2   ,  45074.88  ,  61005.6   ,  47365.92  ,
        52480.8   ,  29783.52  , 159786.72  ,  35964.    , 108691.2   ,
        24988.32  ,  37402.56  ,  23757.552 ,  56423.52  , 133146.72  ,
        90522.72  ,  60845.76  ,  23656.32  ,  35004.96  ,  30103.2   ,
        42570.72  ,  54239.04  ,  46886.4   , 104370.192 ,  39164.5296,
        37992.3696,  45234.72  ,  22803.84  ,  44169.12  ,  30849.12  ,
        50669.28  ,  58448.16  ,  62817.12  ,  35112.0528,  63243.36  ,
        97449.12  ,  39373.92  , 153705.3408,  78215.04  ,  27119.52  ,
       113060.16  ,  34578.72  ,  67399.2   ,  19180.2672, 105228.    ,
        55571.04  , 111834.72  ,  14652.    ,  44968.32  ,  24503.472 ,
        52214.4   ,  68837.76  ,  58288.32  ,  48058.56  ,  15557.76  ,
        55938.672 ,  71128.8   , 140605.92  ,  50243.04  ,  71075.52  ,
        67559.04  ,  60952.32  ,  14651.4672,  60885.72  ,  14646.672 ,
        38148.48  ,  84129.12  ,  60153.12  ,  14865.12  ,  85672.1088,
        19980.    ,  35324.64  ,  69477.12  ,  75071.52  ,  92615.0256,
        74751.84  ,  51729.552 ,  17155.6272,  29696.6736,  76030.56  ,
        50349.6   ,  43103.52  ,  93240.    ,  22697.28  , 117162.72  ,
        46300.8528,  26053.3872,  29463.84  ,  15238.08  ,  63456.48  ,
        21498.48  ,  88178.4   ,  93181.392 , 121584.96  ,  72940.32  ,
       113752.8   , 133679.52  ,  55357.92  ,  84768.48  ,  36975.7872,
        41498.1936,  65510.9568, 144495.36  , 139860.    ,  16303.68  ,
        81465.12  ,  60978.96  , 119826.72  ,  99793.44  ,  93080.16  ,
        89510.4   ,  21791.52  ,  16221.096 , 102564.    , 103523.04  ,
        42038.4528,  31909.392 ,  79920.    ,  28768.536 ,  64755.4464,
       101178.72  ,  31808.16  ,  61751.52  ,  60867.072 , 106506.72  ,
        15930.72  ,  14332.32  ,  53812.8   , 130269.6   ,  90309.6   ,
        18488.16  , 126912.96  ,  39906.72  ,  76137.12  ,  23539.104 ,
       106187.04  ,  54757.9872, 137941.92  ,  81731.52  ,  71661.6   ,
       109010.88  ,  34093.872 ,  28984.32  ,  23176.8   , 111355.2   ,
        16197.12  ,  40439.52  ,  98994.24  ,  61485.12  ,  67932.    ,
        98133.768 ,  39427.2   , 128298.24  ,  72673.92  ,  89084.16  ,
        31254.048 ,  38681.28  ,  13261.392 , 124568.64  ,  95797.44  ,
       103896.    ,  53918.8272,  71928.    ,  47893.392 ,  48538.08  ,
        18115.2   ,  32979.7872,  85194.72  ,  14119.2   ,  65214.72  ,
        32660.64  ,  70489.44  ,  44542.08  ,  64961.1072,  74589.336 ,
        13053.6   ,  27783.9216, 158135.04  ,  80133.12  ,  68184.0144,
        31168.8   ,  73366.56  , 160520.3856,  42486.0048,  39207.1536,
        42517.44  ,  37589.04  ,  41824.8   ,  24634.008 ,  21152.16  ,
        92121.12  ,  59513.2272, 143802.72  ,  28992.312 ,  68198.4   ,
        11934.72  ,  13586.4   ,  30310.992 ,  32921.712 ,  33566.4   ,
       104695.2   ,  52747.2   ,  99153.5472,  44222.4   ,  36496.8   ,
        99367.2   , 141884.64  , 145401.12  ,  39907.2528,  53733.9456,
        81912.1392,  15717.6   , 125154.72  ,  79813.44  ,  89137.44  ,
        32447.52  ,  94305.6   ,  32127.84  ,  28185.12  , 107892.    ,
        78534.72  ,  88977.6   ,  93932.64  ,  64948.32  ,  35616.6144,
        17529.12  ,  24775.2   , 122490.72  , 261018.72  ,  46833.6528,
        23650.992 ,  19127.52  ,  62231.04  ,  74005.92  , 120831.5808,
        20193.12  ,  59886.72  ,  78055.2   ,  41345.28  ,  49656.96  ,
        12733.92  ,  24935.04  ,  34046.4528, 101232.    ,  78801.12  ,
        48304.7136,  93635.3376, 127818.72  ,  59087.52  ,  27753.552 ,
       130536.    ,  62284.32  ,  23976.    ,  14598.72  ,  48964.32  ,
       138474.72  ,  64628.64  ,  84395.52  ,  37775.52  ,  77250.672 ,
        63499.104 ,  19441.872 ,  56689.92  ,  60472.8   ,  63722.88  ,
       167691.8736,  65481.12  ,  22324.32  ,  28504.8   ,  28717.92  ,
        79215.1056,  67026.24  ,  21951.36  ,  99519.048 ,  43580.376 ,
        55091.52  ,  68944.32  ,  26373.6   ,  53168.112 , 109277.28  ,
       149916.6   ,  32639.8608,  29073.2976,  30316.32  ,  16943.04  ,
       101657.7072, 137995.2   ,  51841.44  ,  35644.32  , 100006.56  ,
        22857.12  ,  33110.856 ,  42357.6   ,  98834.4   ,  34898.9328,
        15877.44  ,  76012.4448,  45664.6896,  63936.    ,  89864.1792,
        44574.048 , 194972.832 ,  71847.0144,  26101.872 ,  31409.6256,
       103096.8   ,  34632.    ,  51148.8   , 128884.32  , 111593.8944,
        21887.424 ,  64308.96  ,  35431.2   ,  81784.8   , 175770.72  ,
        60031.1088, 233845.92  ,  25308.    ,  45282.672 ,  83170.08  ,
       152859.7872,  55837.44  ,  99047.52  ,  83063.52  ,  25059.7152,
        62938.0656,  54345.6   , 126273.6   ,  33886.08  , 154458.72  ,
        31003.632 , 191211.264 , 125208.    ,  93985.92  , 100752.48  ,
        71341.92  ,  10810.512 , 104961.6   ,  62071.2   , 124142.4   ,
        43156.8   , 110017.872 ,  39640.32  ,  41558.4   ,  89457.12  ,
       128671.2   ,  51202.08  ,  42081.0768,  20512.8   , 133467.4656,
        40226.4   ,  58075.2   ,  99900.    ,  72354.24  ,  18914.4   ,
       292986.72  ,  63190.08  ,  87912.    , 147832.2864,  17316.    ,
        31435.2   , 163723.5792,  48484.8   ,  38041.3872,  99633.6   ,
        32767.2   ,  54665.28  , 121318.56  ,  46087.2   , 101391.84  ,
        41931.36  , 136343.52  ,  45323.1648,  68464.8   ,  54185.76  ,
       119347.2   ,  94731.84  ,  56210.4   ,  73952.64  ,  39160.8   ,
        90043.2   ,  49816.8   ,  48618.    ,  90576.    ,  36486.144 ,
        24279.696 ,  72988.272 ,  15824.16  , 141138.72  ,  78588.    ,
        49497.12  ,  47952.    ,  32713.92  , 107257.968 , 109170.72  ,
       104588.1072,  79014.24  ,  42037.92  ,  64202.4   , 165168.    ,
        54291.7872,  46939.68  ,  59668.8048,  36496.2672,  69103.6272,
        97236.    ,  38889.072 ,  37725.4368,  15392.592 ,  58874.4   ,
        88924.32  ,  29762.208 , 146946.24  ,  78438.816 ,  94572.    ,
        77788.8   ,  79333.3872, 168045.12  ,  41292.    ,  93772.8   ,
        53759.52  ,  95371.2   ,  45101.52  ,  24808.2336,  43956.    ,
       167778.72  ,  37029.6   , 104587.5744, 149184.    ,  62870.4   ,
       109218.672 ,  53386.56  ,  48751.2   ,  42943.68  ,  63349.92  ,
       101658.24  ,  14418.6336,  61272.    ,  20246.4   , 111301.92  ,
        67132.8   ,  29144.16  ,  58607.4672,  55904.5728,  36443.52  ,
        81997.92  ,  84715.2   , 100550.5488,  64468.8   ,  41025.0672,
        79387.2   , 118761.12  ,  42410.3472,  63159.7104,  55754.3232,
        56476.8   ,  86526.72  ,  57542.4   ,  65480.5872,  91908.    ,
        56633.976 ,  53839.9728,  11231.424 ,  75924.    ,  55922.688 ,
        53280.    , 112065.9552,  78268.32  ,  82351.6992, 122010.6672,
        15339.312 , 139593.6   , 120093.12  ,  37570.392 ,  96916.32  ,
        52746.6672, 102777.12  ,  77682.24  , 211788.    ,  42517.9728,
        70809.12  ,  69264.    ,  25679.8944,  91294.7472,  28771.2   ,
        50083.2   , 172627.2   ,  34433.2656,  39960.    ,  54931.1472,
        20619.36  ,  20965.1472,  18434.3472,  43601.688 ,  34035.264 ,
        26640.    ,  60480.792 ,  62176.1616,  11135.52  ,  75289.968 ,
        80516.2032,  46193.76  ,  21205.44  ,  40980.312 , 104908.32  ,
       146519.4672,  54825.12  , 118601.28  ,  69929.4672,  10442.88  ,
        80612.64  ,  27899.0064, 100965.6   , 109244.2464,  14811.84  ,
        40066.56  ,  32820.48  , 210424.032 ,  41771.52  , 115709.2416,
       130003.2   ,  60888.384 , 122381.496 ,  53807.472 , 124621.92  ,
        18061.92  , 119916.2304,  25515.2592,  79536.384 ,  42010.7472,
       108744.48  ,  94252.32  ,  25414.0272,  74059.2   ,  36177.12  ,
        69530.4   , 114731.5536,  87219.36  ,  44275.68  ,  47686.1328,
        17742.24  ,  48431.52  ,  36816.48  ,  61964.64  ,  70702.56  ,
        19607.04  , 114552.    ,  14492.16  , 109165.392 , 142790.4   ,
       103842.1872,   9270.72  ,  67772.16  ,  78647.1408,  91288.3536,
        78694.56  ,  27804.7008, 186426.72  ,  24988.8528,  85141.44  ,
        25467.84  , 117119.5632,  39267.36  ,  31838.5296,  19276.704 ,
        46620.    , 123876.    ,  30529.44  ,  96596.64  ,  17262.72  ,
        57116.16  ,  23655.7872,  26107.2   ,  47685.6   ,  44382.7728,
        38841.12  ,  15397.92  ,  29303.4672,  42943.1472,  38378.6496,
        33992.64  ,  40705.92  ])

In [18]:
df.reset_index(inplace=True)
df=df.drop("index",axis=1)
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...
1239,Asus,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,4GB,500GB HDD,Nvidia GeForce 920M,Windows 10,2.20,38378.6496
1240,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.80,33992.6400
1241,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.30,79866.7200
1242,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.50,12201.1200
1243,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19,40705.9200

In [19]:
df=pd.read_csv("itunes_music_dataset.csv")
df.head()

,track_id,track_name,artist_name,collection_name,album_artist,genre,rating,track_price,collection_price,release_date,track_time_millis,country,currency,preview_url,artwork_url
0,1624932774,POP!,NAYEON,IM NAYEON,NaN,Dance,Clean,1.29,6.99,2022-06-24T12:00:00Z,168107,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
1,1022164261,Riptide,Vance Joy,Dream Your Life Away (Special Edition),NaN,Alternative,Clean,1.29,9.99,2013-03-22T07:00:00Z,202019,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
2,1207120448,Something Just Like This,The Chainsmokers & Coldplay,Memories...Do Not Open,The Chainsmokers,Dance,Clean,1.29,9.99,2017-02-22T08:00:00Z,247165,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
3,1369380479,lovely,Billie Eilish & Khalid,lovely - Single,NaN,Pop,Clean,1.29,1.29,2018-04-19T12:00:00Z,200187,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
4,1450695872,when the party's over,Billie Eilish,"WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",NaN,Alternative,Clean,1.29,10.99,2018-10-17T07:00:00Z,196077,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...

In [20]:
df["track_id"].unique()

array([1624932774, 1022164261, 1207120448, ..., 1817490077, 1817490076,
       1817507850])

In [21]:
df["track_name"].unique()

array(['POP!', 'Riptide', 'Something Just Like This', ...,
       'Khwabon Ko (Prem Geet / Soundtrack Version)',
       'Suhani Sham Aayi Hai (From "Shaukeeen")',
       'Mujhe Tadpati Rahi (From "Damaad")'], dtype=object)

In [22]:
df["artist_name"].unique()

array(['NAYEON', 'Vance Joy', 'The Chainsmokers & Coldplay', ...,
       'India Sangeet', 'Luniz', 'Anuradha Paudwal'], dtype=object)

In [23]:
df["collection_name"].unique()

array(['IM NAYEON', 'Dream Your Life Away (Special Edition)',
       'Memories...Do Not Open', ..., 'iSouljaBoyTellem (Deluxe Version)',
       'Keith Sweat', 'Operation Stackola'], dtype=object)

In [24]:
df["album_artist"].unique()

array([nan, 'The Chainsmokers', 'Bad Bunny', 'Lady Gaga',
       'Lady Gaga & Bradley Cooper', 'Brandy', 'Various Artists',
       'Lecrae', 'STAR SEEED & ロンリーガール', 'STAR SEEED', 'Betty Carter',
       'Jonathan McReynolds',
       'Randy Newman, Anika Noni Rose & Jim Cummings', 'Randy Newman',
       'Mark Ronson', 'Eydie Gorme', 'Diana Krall',
       'Elton John & Tim Rice, Hans Zimmer',
       'Alan Menken & Howard Ashman', 'Henry Jackman',
       'Luciano Pavarotti', 'Ludovico Einaudi',
       'James McCawley, Kevin Sherwood & Brian Tuey', 'John Williams',
       'Simon Franglen', 'Michael Giacchino', 'Max Richter',
       'London Philharmonic Orchestra & David Parry',
       'Ashton John Jeremy Jr.', 'Dario Marianelli & Jean-Yves Thibaudet',
       'Lorne Balfe, Harold Faltermeyer, Lady Gaga & Hans Zimmer', 'FKJ',
       'RL Grime', 'ZHU', 'Kane Brown', 'Brooke Ligertwood', 'Qiuntellii',
       'Marc E. Bassy & Nic Nac', "Kay'O", 'Hollyn & Weathrman', 'Drake',
       'PARTYNEXTDOOR, DJ Candlestick & OG Ron C',
       'PARTYNEXTDOOR & Drake', 'Majid Jordan', 'Camila Cabello',
       'Ed Sheeran', 'Howard Shore', 'The Weeknd', 'Ariana Grande',
       'ROSALÍA', 'The Weeknd, JENNIE & Lily Rose Depp', 'Kendrick Lamar',
       'Beyoncé', 'Hans Zimmer', "Destiny's Child", 'Luis Fonsi',
       'Shawn Mendes', 'Justin Bieber', 'Queen', 'Michael Jackson',
       'Akon', 'Eminem', 'B.o.B', 'Nicki Minaj',
       'Rihanna & Ludwig Göransson', 'Coldplay', 'JAY-Z',
       'Rihanna & Tems', 'Rihanna', 'David Guetta', 'PARTYNEXTDOOR',
       'Maroon 5', 'Piano Covers', 'Emeli Sandé',
       'Dj Vibes EDM & Dj Beats EDM', 'J Balvin', 'Wham!',
       'Roger Miller & George Bruns', 'A Great Big World', 'JHAYCO',
       'Zara Larsson', 'KPop Demon Hunters Cast, HUNTR/X & Saja Boys',
       'Cardi B', 'Knock2', 'Big Syphe', 'Yng Lvcas', 'Clint Mansell',
       'Nico Parga', 'Basketmouth', 'KDDO', 'Deejay Massive',
       'Morgan Wallen', 'slenderbodies', 'U.S.D.A. & Young Jeezy',
       'Bonobo', 'Piano Deep Relax',
       "White Noise Studio's, Dilip Sen-Sameer Sen, Tony Kakkar, Tanishk Bagchi, Goldboy, Gurmeet Singh, Abhijit Vaghani & Bob",
       'Vishal & Shekhar',
       'Tanishk Bagchi, Amartya Bobo Rahut & Javed-Mohsin',
       'Badshah, Raj Ranjodh & Diljit Dosanjh', 'Buddha Bar',
       'New Years Eve Romantic Song Specialists & Relaxing Instrumental Jazz Academy',
       'Rochak Kohli, Darshan Raval & Jonita Gandhi',
       'Vishal & Shekhar & Julius Packiam',
       'Tanishk Bagchi, B. Praak, Jasleen Royal, Javed Mohsin & Vikram Montrose',
       'Yo Yo Honey Singh, Anand Raj Anand, Amaal Mallik, Zack Knight, Guru Randhawa, Rajat Nagpal, Rochak Kohli & Saurabh Vaibhav',
       'Vishal & Shekhar, Sanchit Balhara, Ankit Balhara, Kumaar, Vishal Dadlani & Kit Bee',
       'Pritam', 'A.R. Rahman', 'Salim-Sulaiman',
       'Mannan Shaah, Badshah & Rishi Rich',
       'Yohani, Jubin Nautiyal, Tanishk Bagchi, Surya Ragunaathan, Surya Ragunnathan, Chamath Sangeeth, Rashmi Virag, Dulan ARX & Mellow D',
       'Sachin-Jigar & Sharib Toshi',
       'Sachet-Parampara, Vishal Mishra, Mithoon, Akhil Sachdeva & Amaal Mallik',
       'Amaal Mallik & Ankit Tiwari',
       'Sonu Nigam, Krishnakali Saha & Sachin-Jigar',
       'Mithoon, Ankit Tiwari & Jeet Gannguli', 'Quebonafide',
       'Varun Jain, Shadab Faridi, Altamash Faridi, Sachin-Jigar & Amitabh Bhattacharya',
       'Shankar Ehsaan Loy',
       'Amaal Mallik, Akhil Sachdeva, Tanishk Bagchi & Bappi Lahiri',
       'Tanishk Bagchi, Vishal & Shekhar, Ankit Tiwari & Rochak Kohli',
       'Jatin-Lalit, Sandesh Shandilya & Aadesh Shrivastava',
       'Sachin-Jigar & Priya Saraiya', 'Amit Trivedi',
       'Sandeep Shirodkar, Panjabi Mc, Laxmikant-Pyarelal, Arko, Mithoon, Gourov-Roshin, Aman Hayer & Pranaay',
       'Sneha Khanwalkar, Badshah & Amaal Mallik',
       'A.R. Rahman & Irshad Kamil',
       'Ram Sampath, Divyanidhi Sharma, Prashant Pandey & Swanand Kirkire',
       'Sachin-Jigar', 'Raj Ranjodh, Akshay & IP & Vishal Mishra',
       'Shirish Kunder & Vishal & Shekhar',
       'Mithoon, Amaal Mallik, Epic Bhangra & Jeet Gannguli',
       'Diddy - Dirty Money',
       'Tanishk Bagchi, Lijo George, Dj Chetas & Thaman S.',
       'Manan Bhardwaj, Bhupinder Babbal, Jam8, Manoj Muntashir, Shreyas Puranik, Siddharth-Garima, Harshavardhan Rameshwar, Raj Shekhar, Vishal Mishra, Jaani & Ashim Kemson',
       'Ajay-Atul', 'Jam8',
       'Tanishk Bagchi, Panjabi Mc, Rochak Kohli & Jam8',
       'Anirudh Ravichander, Irshad Kamil, Kumaar, Raja Kumari & Mohamed El Maghribi',
       'Amaal Mallik, Ankit Tiwari & Meet Bros Anjjan',
       'Tanishk Bagchi, Neeraj Rajawat, Mitraz, Raghav, Nina Mathur, Sachin-Jigar & Indraneel',
       'Surinder Sangha', 'Ali Sethi & Shae Gill', 'AP Dhillon',
       'Annural Khalid & Maanu', 'Diljit Dosanjh, Snappy & Rav Hanjra',
       'Hasan Raheem', 'Sidhu Moose Wala', 'Harman Hundal', 'Taste Test',
       'Vanessa-Mae & Royal Philharmonic Orchestra',
       'Thaman S., Sri Vardhini, Aditi Bhavaraju, Satya Yamini, Roshini JKV & Tejaswini',
       'Yuvan Shankar Raja', 'Arivu & G.V. Prakash Kumar',
       'Anirudh Ravichander',
       'Rohini, Harris Jayaraj, Pritt & dilushselva',
       'Pritam & Sandesh Sandilya',
       'Santhosh Narayanan, Shenoy Nagar Shanmugam & Sindhai Nathan',
       'James Vasanthan',
       'Adi Shankara, Andal Pasuram, Ilango Krishnan, Kudavayil Keerathanar & A.R. Rahman',
       'Vairamuthu & A.R. Rahman', 'Vidyasagar', 'Santhosh Narayanan',
       'Anirudh Ravichander, Super Subu, Arunraja Kamaraj & Vignesh Shivan',
       'A.R. Rahman, Sri Rascol, Aaryan Dinesh Kanagaratnam & Vignesh Shivan',
       'Ilaiyaraaja & Vaalee', 'Ilaiyaraaja & Viswanathan',
       'Thaman S. & Vivek', 'Sam C.S.', 'Sean Roldan', 'Harris Jayaraj',
       'Vivek, G.V. Prakash Kumar, Dhanush & Jonita Gandhi',
       'Sai Abhyankkar, Anirudh Ravichander & Super Subu',
       'Darbuka Siva, Aaryan Dinesh Kanagaratnam, Madhan Karky & Thamarai',
       'Anirudh Ravichander, Shilpa Rao & Arunraja Kamaraj',
       'Ghibran, Vaisagh, Shabir Sulthan & Viveka', 'Thaman S.',
       'Govind Vasantha', 'Anirudh Ravichander & Vijay',
       'M.M. Keeravani, Seetharama Shastry & Vennelakanti',
       'Sublahshini, Anirudh Ravichander & Krishna Kanth',
       'Krishna Kanth, Thaman S. & Sid Sriram',
       'Anudeep Dev, GowraHari & Krishna Saurabh Surampalli',
       'Sunny M.R., Vinayak Sasikumar, Krishna Kanth & Roll Rida',
       'Mani Sharma', 'Bheems Ceciroleo',
       'Thaman S., Roll Rida, Rahul Nambiar, Lady Kash, Rahul Sipligunj & Blazee',
       'Devi Sri Prasad', 'Krishna Kanth, GowraHari & Armaan Malik',
       'Arko, Yo Yo Honey Singh, Mithoon, Devi Sri Prasad & Sajid-Wajid',
       'Adi Shankara, Anantha Sriram, Chandrabose, Ramajogayya Sastry & A.R. Rahman',
       'Bhuvana Chandra & Harris Jayaraj', 'Krishna Kanth & Ravi Basrur',
       'Gopi Sundar', 'Krishna Kanth, Ravi Basrur & Harini Ivaturi',
       'Anantha Sriram, A.R. Rahman, A. R. Reihana & Bamba Bakya',
       'Thaman S., Raghuram, Sanjana Kalmanje & Sid Sriram',
       'Devi Sri Prasad & Sirivennela Sitarama Sastry',
       'Anantha Sriram & A.R. Rahman', 'Jakes Bejoy',
       'Harris Jayaraj & Kula Sekhar', 'Shakthikanth Karthick',
       'Ravi Basrur & Ramajogayya Shastri', 'Sricharan Pakala',
       'Justin Prabhakaran', 'Devi Sri Prasad & Ramajogayya Sastry',
       'Tanishk Bagchi, Guru Randhawa, Badshah & Shankar Ehsaan Loy',
       'Radhan', 'Srabanti Chatterjee',
       'Babu Singh Maan, Charanjit Ahuja, Hanumankind, Indiwar, Irshad Kamil, Jasmine Sandlas, Lal Chand Yamla Jatt, Majrooh Sultanpuri, Raj Ranjodh, Reble, Roshan, Sahir Ludhianvi, Shashwat Sachdev & Simran Choudhary',
       'Arijit Singh, Jonita Gandhi, Ranveer Singh, Pritam, Madan Mohan & Amitabh Bhattacharya',
       'Jeet Gannguli, Mithoon & Ami Mishra',
       'Vishal & Shekhar, Dr Zeus, Manj Musik & John Stewart Eduri',
       'Arijit Singh, Shreya Ghoshal, Pritam & Amitabh Bhattacharya',
       'Ankit Tiwari, Mithoon, Rabbi Ahmed & Adnan Dhool',
       'Vishal & Shekhar & Sanchit Balhara',
       'Pritam & Amitabh Bhattacharya',
       'Sharib Toshi, Sridevi Keshavan, Janaka Atugoda, Juno Reactor, Rahul Bhatt & Itek Bhutani',
       'Mithoon & Jasleen Royal', 'Jeet Gannguli',
       'Sanjay Leela Bhansali & Siddharth-Garima',
       'Sanjay Leela Bhansali & A M Turaz', 'Manoj Muntashir',
       'Sanjay Leela Bhansali, Shreyas Puranik & Prashant Ingole',
       'Pritam, Swanand Kirkire, IP Singh, Javed Akhtar, Irshad Kamil, Varun Grover, Kumaar, Amitabh Bhattacharya, Shekhar Ravjiani & Traditional',
       'Tanishk Bagchi, Rishi Rich & Sachet-Parampara',
       'Pritam, Amitabh Bhattacharya & Charan',
       'Sachin-Jigar & Amitabh Bhattacharya',
       'Sajid-Wajid, Manj Musik, Mustafa Zahid & Bilal Saad',
       'Arijit Singh, Shreya Ghoshal, Shadab Faridi, Altamash Faridi, Pritam & Amitabh Bhattacharya',
       'Amaal Mallik',
       'Mithoon, Abhijit Vaghani, Kalyanji-Anandji, Meet Bros, R.D. Burman & Gourov Roshin',
       'Payal Dev, Mika Singh, Gaurav Chatterji & Jaan Nissar Lone',
       'Sandeep Shirodkar, Anu Malik, Sajid-Wajid & Meet Bros',
       'Pritam, Irshad Kamil & Amitabh Bhattacharya',
       'Tanishk Bagchi, Rochak Kohli, Arko & Sajid-Wajid',
       'Pritam, Mithoon, Arko, Yo Yo Honey Singh & Anupam Amod',
       'Ravi Basrur & Tanishk Bagchi',
       'Neha Kakkar, Manj Musik, Herbie Sahara, Tanishk Bagchi & RDB',
       'Tanishk Bagchi, A.R. Rahman, Badshah, Intense, Sachin-Jigar, Guru Randhawa, Harsh Upadhyay, Shankar Ehsaan Loy, Gurinder Seagal & Garry Sandhu',
       'Neha Kakkar', 'Yo Yo Honey Singh',
       'Anu Malik, Sohail Sen & Tanishk Bagchi',
       'Vipin Patwa, Amaal Mallik, Tanishk Bagchi, Manj Musik, Atul Sharma & Rochak Kohli',
       'Sachin-Jigar, Tanishk Bagchi, B. Praak, Meet Bros, Rochak Kohli, DJ Chetas, Kimera, Vayu, Jaani, Kumaar & Gurpreet Saini',
       'Badshah',
       'Tanishk Bagchi, Sukh-E Muzical Doctorz, Meet Bros, Amartya Bobo Rahut, Gaurav Chatterji, Parag Chhabra & Rishi-Siddharth',
       'Tony Kakkar, Tanishk Bagchi, Anand-Milind, Sachet-Parampara, Rochak Kohli & Lijo George-Dj Chetas',
       'Javed Mohsin, Tanishk Bagchi & Farhad Samji',
       'Shashwat Sachdev, Jubin Nautiyal & Neha Kakkar', 'Guru Randhawa',
       'Tulsi Kumar', 'Sachin-Jigar, Mika Singh, Neha Kakkar & Vayu',
       'Mika Singh, Neha Kakkar & Vayu',
       'Tanishk Bagchi, Jasbir Jassi, Shyam Bhateja, Anand-Milind, Payal Dev, Badshah & Rochak Kohli',
       'Guru Randhawa, Badshah & Gurinder Seagal',
       'Sachin-Jigar & B. Praak', 'Pritam & Mayur Puri', 'Emiway Bantai',
       'Amaal Mallik, Rishi Rich, Yash Anand & Gourov-Roshin',
       'Narasimha Nayak',
       'Badshah, Guru Randhawa, Preet Hundal & Amit Trivedi',
       'Badshah, Anuj Garg & Julius Packiam', 'B. Ajaneesh Loknath',
       'Shreya Ghoshal, Kumar Shanu & Zubeen Garg', 'Ram Sampath',
       'Sachin Gupta',
       'Vishal & Shekhar, Julius Packiam & Ali Abbas Zafar',
       'Himesh Reshammiya & Pritam',
       'Kailash-Paresh-Naresh, Shankar Ehsaan Loy & Bohemia', 'Anu Malik',
       'Sajid Wajid, Sohail Sen & Julius Packiam',
       'Samuel Shetty, Akanksha Nandrekar, Javed Khan, Mohsin Shaikh, Jeet Gannguli, Abhishekh Mishra & Tanishk Bagchi',
       'Pritam, Shreya Ghoshal, Tushar Joshi & Amitabh Bhattacharya',
       'Raju Singh', 'Vishal & Shekhar & Vinil Mathew',
       'Rohan-Rohan, Vikram Montrose & A.R. Rahman',
       'Himesh Reshammiya, Meet Bros Anjjan, Yo Yo Honey Singh & Kumaar',
       'Sajid-Wajid & Lalit Pandit', 'Sajid-Wajid', 'Himesh Reshammiya',
       'Shantanu Moitra',
       'Shantanu Moitra, Ankit Tiwari, Ajay-Atul & Rajkumar Hirani',
       'M.M. Keeravani',
       'Bombay Rockers, Sunny Bawra, Inder Bawra & Ankit Tiwari',
       'Sajid Wajid', 'Rochak Kohli & Meet Bros', 'Rajesh Roshan',
       'Shashwat Sachdev',
       'Manj Musik, Chirrantan Bhatt, Meet Bros & Vishal Khurana',
       'Payal Dev, Tanishk Bagchi, Kalyanji-Anandji, Laxmikant-Pyarelal, Meet Bros, Aditya Dev, Sanjay Chaudhary & Yo Yo Honey Singh',
       'Tanishk Bagchi, Nusrat Fateh Ali Khan, Yo Yo Honey Singh & Payal Dev',
       'Guru Randhawa, Soumik Sen, Rochak Kohli, Bappi Lahiri, Kunaal-Rangon, Agnee & Krsna Solo',
       'Tanishk Bagchi, Javed Mohsin & Jaani',
       'Tanishk Bagchi, Nayeem - Shabir, Yo Yo Honey Singh & Sajid-Wajid',
       'Jubin Nautiyal', 'Devi Sri Prasad & Amitabh Bhattacharya',
       'Nitin Kakkar', 'Jeet Gannguli, Chirantan Bhatt & Nadeem Shravan',
       'Tony Kakkar, Meet Bros, Vivek Kar & Jeet Gannguli', 'Jatin-Lalit',
       'Madan Mohan', 'Laxmikant-Pyarelal', 'Uttam Singh', 'R.D. Burman',
       'Shankar - Jaikishan', 'Khaiyyaam',
       'Lata Mangeshkar & Madan Mohan', 'Kishore Kumar', 'Raamlaxman',
       'Rahul Sharma', 'Lata Mangeshkar & Usha Mangeshkar',
       'Kalyanji-Anandji', 'Usha Khanna & Kamal Joshi', 'S.D. Burman',
       'Shiv-Hari', 'Bhupen Hazarika', 'Ilaiyaraaja', 'Lata Mangeshkar',
       'Naushad & Ghulam Mohammed', 'Salil Chowdhury', 'Raam Laxman',
       'Bappi Lahiri', 'G.V. Prakash Kumar', 'Ravi', 'Jaidev',
       'O. P. Nayyar', 'Naushad', 'Asha Bhosle & Mohd. Rafi',
       'Laxmikant-Pyarelal & DJ Remy', 'Mohd. Rafi', 'Roshan',
       'Jugal Kishore- Tilakraj',
       'Laxmikant-Pyarelal & Majrooh Sultanpuri', 'Asha Bhosle',
       'Himesh Reshammiya, Kiran Kamath, Dj A Sen, Dj Amann Nagpal & Teenu Arora',
       'Sachin-Jigar, Priya Saraiya, Som & Vayu',
       'Shantanu Moitra, Ankit Tiwari, Prashant Pillai, Advaita & Gaurav Godkhindi',
       'Amaal Mallik, Neeraj Shridhar & Sukriti Kakar',
       'Bramfatura, Mikey McCleary, Maatibaani, Prashant Pillai, Gaurav Godkhindi, The Light Years Explode & Dub Sharma',
       'S . N . Tripathi', 'Shankar Ehsaan Loy & Daniel B.George',
       'Jiiva & D. Imman', 'Shaan Rahman & Manu Manjith',
       'The Pussycat Dolls', 'A.R. Rahman & Rajat Dholakia',
       'A.R. Rahman & P.K. Misra',
       'Ilango Krishnan, Kabilan, Siva Ananth, A.R. Rahman & krithika Nelson',
       'Diljit Dosanjh', 'Shashwat Sachdev & Jasleen Royal',
       'Amit Trivedi, Shellee, Shri Shiv Kumar Batalvi & Varun Grover',
       'Sachin-Jigar, Guru Randhawa & Akash D',
       'Jatinder Shah, Nick Dhammu & Diljit Dosanjh',
       'Nick Dhammu, Ranbir Singh & Veet Baljit',
       'Tanishk Bagchi, Sachet-Parampara, Aditya Rikhari & Amaal Mallik',
       'Thaman S., Diljit Dosanjh & Dhee',
       'Byg Byrd, Laddi Gill, Qaistarx & Young Blood',
       'Meet Bros Anjjan, Yo Yo Honey Singh, Pranay Rijia & Chirantan Bhatt',
       'P.A. Deepak, Chirantan Bhatt & Kalyanji-Anandji',
       'Meet Bros, Yo Yo Honey Singh, Mithoon & Ilaiyaraaja',
       'Nijjar, Yo Yo Honey Singh & Gurlez Akhtar',
       'Tanishk Bagchi, Ashok Mastie, Sachet-Parampara, Vishal Mishra, Ramji Gulati, Channi Rakhala, Shabbir Ahmed, Rashmi Virag, Raj Shekhar, Siddharth - Garima & Kumaar',
       'Yo Yo Honey Singh, Dr Zeus, Tiger Style, Indeep Bakshi, Jatinder Shah, Meet Bros Anjjan, Millind Gaba & Jassi Katyal',
       'Himesh Reshammiya, Sajid-Wajid & Sandeep Chawtha',
       'Yo Yo Honey Singh, Hitesh Sonik & Vishal & Shekhar',
       'Pritam & Tanishk Bagchi',
       'Yo Yo Honey Singh, White Noise Collectives, Tanishk Bagchi & Kratex',
       'Meet Bros Anjjan, Ram Sampath & Yo Yo Honey Singh',
       'Jeet Gannguli, Meet Bros Anjjan, Ankit Tiwari & Yo Yo Honey Singh',
       'Yo Yo Honey Singh, Raftaar & Prashant Vadhyar', 'Mika Singh',
       'Yo Yo Honey Singh, Chinmayi Sripada & Gopi Sundar',
       'Narasimha Nayak, Ikka, Hommie Dilliwala, Singhsta, Yo Yo Honey Singh, Jamil Ahmed, Bilal Saeed & Shabbir Ahmed',
       'Meet Bros Anjjan, Anu Malik, Mika Singh, Music Mg, Siddhant Madhav, Yo Yo Honey Singh & Abhishek Ray',
       'Gurjit Gill, Guru Randhawa & Lavish Dhiman',
       'Guru Randhawa, Rajat Nagpal, Haji Springer, Tanishk Bagchi, Laxmikant-Pyarelal, Amartya Rahut (Bobo) & Santanu Ghatak',
       'Tanishk Bagchi, Abrar Ul Haq, Kanishk Seth, Kavita Seth, Pozy, Vishal Shelke, Diesby, Chapter6 & Atul Sharma',
       'Gill Machhrai, Guru Randhawa, Rony Ajnali & Kiran Bajwa',
       'Millind Gaba & Guru Randhawa',
       'Guru Randhawa, Rick Ross & DJ Shadow',
       'Sachet Tandon, Parampara Thakur & Sachet-Parampara',
       'Various Artist',
       'Pasek & Paul, Hugh Jackman, Zac Efron & Zendaya', 'Amjad Nadeem',
       '5 Alarm Music', 'Thaman S., Suchithra & Sreejo',
       'Kittu Vissapragada, Sinjith Yerramilli & Swaroop Goli',
       'Gopi Sundar, Shree Mani & Krishna Kanth',
       'Sankar Sharma, Ranjith Sankar, Sandra Madhav, Arathi Mohan, Anu Elizabeth Jose, Vivek Muzhakkunnu & Sandhoop Narayanan',
       'Thaman S. & Achu Rajamani',
       'M.M. Keeravaani, Aditya Iyengar, Inaganti Sundar & Koodala Sangayya',
       'Chakri', 'M.M. Keeravaani, Anantha Sriram & Wasistha Varma',
       'Nitin Arora, Sony Chandy & Sameer',
       'Sony Komanduri, Sandilya Pisapati & Pasunoori Ravinder',
       'J. Bhaktavatsalam', 'Sony Thulewal & Kanwar Grewal',
       'Sinjith Yerramilli, Kittu Vissapragada & Swaroop Goli',
       'Afzal Yusuf', 'Nitin Arora, Sony Chandy & Sameer Anjaan',
       'Nagavelli Vidya Sagar, Krish Jagarlamudi & ES Murthy',
       'Sony no beat, Mc India & Mc J Mito', 'M.S. Viswanathan & Veturi',
       'Simon K King, Vedshanker & Dharan Kumar', 'Keethan',
       'Kishore Kumar & Asha Bhosle'], dtype=object)

In [25]:
df["track_price"].unique()

array([ 1.29, -1.  ,   nan,  0.69,  0.99])

In [26]:
df=pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/dirty_cafe_sales.csv")
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [27]:
df["Transaction ID"].unique()

array(['TXN_1961373', 'TXN_4977031', 'TXN_4271903', ..., 'TXN_5255387',
       'TXN_7695629', 'TXN_6170729'], dtype=object)

In [28]:
df["Item"].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', nan, 'ERROR', 'Juice', 'Tea'], dtype=object)

In [29]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [30]:
df["Item"]=df["Item"].replace(["UNKNOWN", None], "Unknown_Item")
df.isna().sum()

Transaction ID         0
Item                   0
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [31]:
df["Quantity"].unique()

array(['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan], dtype=object)

In [34]:
df["Price Per Unit"]=df["Price Per Unit"].replace(["ERROR","UNKNOWN"],"0")
df["Price Per Unit"] = pd.to_numeric(df["Price Per Unit"], errors='coerce').fillna(0).astype(int)
df["Price Per Unit"].unique()
df.isnull().sum()

Transaction ID         0
Item                   0
Quantity             138
Price Per Unit         0
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [35]:
df["Total Spent"]=df["Total Spent"].replace(["ERROR","UNKNOWN"],"0")
df["Total Spent"] = pd.to_numeric(df["Total Spent"], errors='coerce').fillna(0).astype(int)
df["Total Spent"].unique()
df.isnull().sum()

Transaction ID         0
Item                   0
Quantity             138
Price Per Unit         0
Total Spent            0
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [36]:
df["Payment Method"]=df["Payment Method"].replace(["ERROR","UNKNOWN"],"0")
df["Payment Method"] = pd.to_numeric(df["Payment Method"], errors='coerce').fillna(0).astype(int)
df["Payment Method"].unique()
df.isnull().sum()

Transaction ID         0
Item                   0
Quantity             138
Price Per Unit         0
Total Spent            0
Payment Method         0
Location            3265
Transaction Date     159
dtype: int64

In [37]:
df["Location"]=df["Location"].replace(["ERROR","UNKNOWN"],"0")
df["Location"] = pd.to_numeric(df["Location"], errors='coerce').fillna(0).astype(int)
df["Location"].unique()
df.isnull().sum()

Transaction ID        0
Item                  0
Quantity            138
Price Per Unit        0
Total Spent           0
Payment Method        0
Location              0
Transaction Date    159
dtype: int64

In [38]:
df["Transaction Date"]=df["Transaction Date"].replace(["ERROR","UNKNOWN"],"0")
df["Transaction Date"] = pd.to_numeric(df["Transaction Date"], errors='coerce').fillna(0).astype(int)
df["Transaction Date"].unique()
df.isnull().sum()

Transaction ID        0
Item                  0
Quantity            138
Price Per Unit        0
Total Spent           0
Payment Method        0
Location              0
Transaction Date      0
dtype: int64

In [39]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2,4,0,0,0
1,TXN_4977031,Cake,4,3,12,0,0,0
2,TXN_4271903,Cookie,4,1,0,0,0,0
3,TXN_7034554,Salad,2,5,10,0,0,0
4,TXN_3160411,Coffee,2,2,4,0,0,0
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2,4,0,0,0
9996,TXN_9659401,Unknown_Item,3,0,3,0,0,0
9997,TXN_5255387,Coffee,4,2,8,0,0,0
9998,TXN_7695629,Cookie,3,0,3,0,0,0
9999,TXN_6170729,Sandwich,3,4,12,0,0,0