<a href="https://colab.research.google.com/github/Sanjana6653/DataScience-Tasks/blob/main/tax_trip_pricing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Linear Regression

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# ML LIBRARIES
from sklearn.linear_model import LinearRegression
from sklearn import datasets
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error

In [3]:
df = pd.read_csv("/content/taxi_trip_pricing (1).csv")
df

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
1,47.59,Afternoon,Weekday,1.0,High,Clear,NaN,0.62,0.43,40.57,NaN
2,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
3,30.33,Evening,Weekday,4.0,Low,NaN,3.48,0.51,0.15,116.81,36.4698
4,NaN,Evening,Weekday,3.0,High,Clear,2.93,0.63,0.32,22.64,15.6180
...,...,...,...,...,...,...,...,...,...,...,...
995,5.49,Afternoon,Weekend,4.0,Medium,Clear,2.39,0.62,0.49,58.39,34.4049
996,45.95,Night,Weekday,4.0,Medium,Clear,3.12,0.61,NaN,61.96,62.1295
997,7.70,Morning,Weekday,3.0,Low,Rain,2.08,1.78,NaN,54.18,33.1236
998,47.56,Morning,Weekday,1.0,Low,Clear,2.67,0.82,0.17,114.94,61.2090
999,22.85,Morning,Weekend,3.0,Medium,Clear,4.34,NaN,0.23,29.69,45.4437

**Exploratory Data Analysis**

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Trip_Distance_km       950 non-null    float64
 1   Time_of_Day            950 non-null    object
 2   Day_of_Week            950 non-null    object
 3   Passenger_Count        950 non-null    float64
 4   Traffic_Conditions     950 non-null    object
 5   Weather                950 non-null    object
 6   Base_Fare              950 non-null    float64
 7   Per_Km_Rate            950 non-null    float64
 8   Per_Minute_Rate        950 non-null    float64
 9   Trip_Duration_Minutes  950 non-null    float64
 10  Trip_Price             951 non-null    float64
dtypes: float64(7), object(4)
memory usage: 86.1+ KB

In [5]:
df.isnull().sum()

Trip_Distance_km         50
Time_of_Day              50
Day_of_Week              50
Passenger_Count          50
Traffic_Conditions       50
Weather                  50
Base_Fare                50
Per_Km_Rate              50
Per_Minute_Rate          50
Trip_Duration_Minutes    50
Trip_Price               49
dtype: int64

In [6]:
df["Trip_Distance_km"].unique()

array([ 19.35      ,  47.59      ,  36.87      ,  30.33      ,
                nan,   8.64      ,   3.85      ,  43.44      ,
        30.45      ,  35.7       ,  48.53      ,  41.79      ,
        11.4       ,   9.91      ,   9.99      ,  15.91      ,
        26.71      ,  22.17      ,  15.27      ,  30.98      ,
         7.84      , 105.94355004,  18.95      ,  23.35      ,
        39.47      ,  10.78      , 138.09832791,  30.03      ,
         3.28      ,  30.77      ,   9.36      ,   4.19      ,
        47.5       ,  48.32      ,  40.61      ,  15.93      ,
         5.79      ,  34.53      ,  22.57      ,   6.98      ,
        25.26      ,   2.69      ,  45.56      ,  13.68      ,
        33.46      ,  16.27      ,  26.48      ,  27.79      ,
        10.06      ,  48.51      ,  38.98      ,  47.04      ,
        44.85      ,  30.3       ,  46.17      ,   5.34      ,
        10.6       ,   3.22      ,  16.94      ,  20.05      ,
        14.3       ,  41.61      ,  18.48      , 146.06704716,
        27.59      ,   7.91      ,  40.31      ,   4.65      ,
        49.36      ,  38.84      ,  10.74      ,   1.27      ,
        40.96      ,  35.64      ,  36.72      ,  38.79      ,
         4.63      ,  18.56      ,   6.68      ,  43.29      ,
        31.54      ,  17.21      ,   4.11      ,  16.93      ,
        36.75      ,  44.47      ,  24.14      ,   6.86      ,
        35.95      ,  38.28      ,  28.5       ,  38.78      ,
        26.61      ,  21.95      ,   2.25      ,   6.29      ,
         2.54      ,  32.18      ,  16.4       ,  25.92      ,
        45.47      ,  13.22      ,  21.11      ,  38.02      ,
       112.83095829,   4.77      , 102.74755621,  46.56      ,
        40.6       ,  32.04      ,  43.7       ,  40.38      ,
        10.14      ,  44.74      ,  27.43      ,  40.56      ,
        44.91      ,  16.58      ,   6.39      ,  12.17      ,
        21.93      ,  41.08      ,  43.18      ,   1.34      ,
        26.03      ,  21.45      ,  11.88      ,   6.87      ,
        17.54      ,  16.84      ,  26.42      ,  18.82      ,
        48.62      ,  48.16      , 109.61608205,  15.74      ,
        14.96      ,   2.81      ,  30.87      ,  25.63      ,
         3.52      ,  14.65      ,  45.51      ,  12.74      ,
         8.1       ,  24.98      ,  49.3       ,  12.86      ,
        33.93      ,  38.32      ,  12.64      ,  36.68      ,
        19.02      ,  31.98      ,  27.25      ,   5.42      ,
        41.93      ,   3.        ,  29.95      ,  34.2       ,
         1.81      ,  26.09      ,  12.1       ,  32.61      ,
         9.54      ,  34.86      ,  19.95      ,  46.9       ,
         7.74      ,  17.71      ,   6.56      ,  46.31      ,
        43.99      ,  13.64      ,  33.34      ,  41.04      ,
        28.2       ,  26.95      ,  12.85      ,   5.56      ,
        45.12      ,  32.02      ,  17.61      ,  18.11      ,
        39.21      ,  32.46      ,   5.12      ,   8.92      ,
        45.03      ,  30.72      ,   1.45      ,   5.97      ,
        33.51      ,   1.25      ,   8.88      ,  27.89      ,
        34.9       ,  32.95      ,  11.99      ,  35.9       ,
        12.63      ,  37.58      ,  32.83      ,  42.61      ,
        33.22      ,  28.85      ,   5.59      ,  13.99      ,
       130.80900131,  48.68      ,  20.26      ,  44.71      ,
        31.93      ,  39.95      ,  29.27      ,  25.13      ,
        36.4       ,  14.76      ,   2.19      ,  32.63      ,
         9.68      ,  47.08      ,  47.74      ,  45.83      ,
        19.14      ,   1.76      ,  46.49      ,  21.98      ,
        48.37      ,  48.22      ,  42.8       ,  15.43      ,
        19.87      ,  42.71      ,  16.53      ,   9.31      ,
        28.28      ,  46.87      ,  35.11      ,  28.93      ,
         5.76      ,  31.14      ,  49.51      ,   7.86      ,
        26.4       ,  37.3       ,  35.15      , 116.19606362,
       139.06223019,  40.66      ,  40.7       ,  43.49      ,
        45.75      ,  26.06      ,  25.57      ,  40.12      ,
        32.85      ,  35.4       ,  39.99      ,  44.61      ,
        17.56      ,   5.61      ,  29.34      ,   2.76      ,
        23.81      , 100.38042001,  15.04      ,   2.49      ,
         2.83      ,  41.31      ,  18.65      ,   7.23      ,
        26.59      ,  38.73      ,  11.58      ,  31.52      ,
         5.18      ,   3.53      ,  27.04      , 145.74705995,
        32.23      ,  36.58      ,  48.82      ,  26.3       ,
        16.82      ,  39.96      ,  14.27      ,  22.51      ,
         4.84      ,   2.24      ,  48.17      ,  41.96      ,
        35.1       ,  21.04      ,   9.49      ,   8.67      ,
        13.26      ,  27.91      ,  36.02      ,  33.35      ,
        14.72      ,  47.79      ,  37.16      ,  28.16      ,
        21.56      ,  13.14      ,  18.44      ,  38.13      ,
         1.71      ,   6.69      ,   3.25      ,  42.92      ,
        35.48      , 116.66768073,  25.09      ,  24.2       ,
        22.26      ,  31.18      ,  32.12      ,  19.36      ,
        31.67      ,  25.65      ,  42.97      ,  33.28      ,
         8.98      ,   4.46      ,  32.48      ,   2.3       ,
        47.07      ,  29.2       ,  20.02      ,  32.52      ,
        23.45      ,  27.74      ,  47.13      ,  19.92      ,
        45.36      ,  10.59      ,   4.4       ,   5.94      ,
         1.89      ,   5.63      ,  34.47      ,   4.49      ,
        16.63      ,  42.4       ,   2.14      ,  40.91      ,
        14.81      ,   6.79      ,  35.14      ,  31.82      ,
        44.        ,  37.02      ,  40.37      ,  14.82      ,
         9.69      ,  37.78      ,  40.53      ,  49.53      ,
        21.22      ,  19.23      ,  39.04      ,  17.7       ,
        46.61      ,  43.06      ,  22.02      ,  37.79      ,
        37.97      ,   6.05      ,  25.76      ,  41.5       ,
        44.88      ,  20.07      ,   1.53      ,   5.47      ,
       104.37179089,  47.55      ,  47.58      ,  29.1       ,
        31.96      ,  22.97      ,  15.37      ,  33.95      ,
        37.87      ,  39.79      ,  39.69      ,  25.23      ,
        27.93      ,  22.63      ,  44.5       ,   6.74      ,
         8.01      ,  38.31      ,  31.29      ,   5.96      ,
        35.35      ,   4.57      ,  41.27      ,   5.16      ,
        49.35      ,  19.34      ,  19.16      ,  40.83      ,
        47.42      ,  37.92      ,  19.44      ,   5.09      ,
        39.08      ,  28.36      ,  21.79      ,  45.41      ,
         6.45      ,  25.14      ,   1.56      ,  23.96      ,
         3.76      ,   6.82      ,   6.76      ,  32.81      ,
        37.56      ,  29.59      ,  48.15      ,  19.37      ,
        15.        ,  43.56      ,  11.96      ,  48.2       ,
        48.52      ,   3.11      ,  44.67      ,  26.86      ,
        49.66      ,  28.14      ,  48.5       ,  26.63      ,
        31.84      , 107.78683196,  23.27      ,  31.75      ,
        29.63      ,  45.16      ,   3.23      ,  14.77      ,
        47.57      ,  44.62      ,  23.33      ,  31.39      ,
        14.59      ,  10.22      ,  23.72      ,  18.31      ,
        29.6       ,   4.81      ,  48.75      ,  49.32      ,
        35.21      ,  27.27      ,  16.17      ,  40.88      ,
        34.55      ,   8.97      ,  45.64      ,  41.3       ,
        47.54      ,  36.56      ,  31.06      ,  21.49      ,
        46.7       ,   2.29      ,  19.45      ,  40.72      ,
        49.38      ,   8.37      ,  30.11      ,  19.66      ,
        42.26      ,  42.08      ,  23.97      ,  21.33      ,
        14.4       ,  43.37      ,  49.99      , 139.47651458,
        28.22      ,  38.68      ,  47.29      ,  42.63      ,
        13.12      ,  23.08      ,   7.33      ,  47.75      ,
        30.7       ,  12.2       ,  33.91      ,  18.55      ,
        26.5       ,  26.49      ,  42.76      ,  28.04      ,
        28.49      ,  43.96      ,  20.77      ,   7.57      ,
         2.41      ,  38.        ,  31.4       ,  35.5       ,
        11.44      ,   7.68      ,  18.18      ,  29.91      ,
        20.22      ,  22.44      ,  45.3       ,  18.06      ,
        26.19      ,  39.4       ,  20.43      ,  31.48      ,
        43.26      ,  47.53      ,   8.21      ,  46.4       ,
        25.11      ,  13.65      ,  23.5       ,  49.02      ,
        17.11      ,  12.77      ,   4.72      ,   7.32      ,
       122.82019098,   8.44      ,   7.8       ,  32.4       ,
        17.94      ,  44.94      ,  24.22      ,  33.71      ,
         9.44      ,  10.42      ,   9.28      ,   9.67      ,
         5.35      ,   6.91      ,  23.58      ,  11.11      ,
        18.85      ,  25.67      ,  34.83      ,   2.93      ,
        40.17      ,  31.77      ,   5.01      ,  43.81      ,
        46.12      , 138.76388715,  14.57      ,  40.5       ,
        37.66      ,  10.04      ,  11.26      ,  19.15      ,
        24.74      ,  19.08      ,  23.66      ,  37.63      ,
         2.8       ,  13.37      ,  44.87      ,  26.07      ,
        27.07      ,   6.25      ,  22.92      ,  27.1       ,
        12.88      ,  14.19      ,  19.49      ,   1.98      ,
        11.36      ,  17.05      ,  44.64      ,  30.09      ,
        39.67      ,  25.42      ,   5.26      ,  27.32      ,
        29.76      ,  37.53      ,  22.15      ,   7.25      ,
        14.91      ,  18.79      ,  32.65      ,  28.97      ,
        18.45      ,  49.34      ,  30.68      ,  12.62      ,
         5.99      ,   8.49      ,  13.05      ,   8.87      ,
        14.97      ,   9.5       ,   4.93      ,  26.7       ,
        49.14      ,   6.49      ,  20.49      ,  43.41      ,
         9.37      ,  33.76      ,  46.54      ,  29.01      ,
        38.71      ,  10.17      ,  16.86      ,  21.85      ,
        25.87      ,   6.63      ,  30.92      ,  15.14      ,
        29.48      ,   8.56      ,  24.58      ,   3.54      ,
        17.49      ,   7.59      ,  16.8       ,  40.68      ,
        13.48      ,  34.39      ,  38.25      ,  30.19      ,
        24.11      ,  21.18      ,  18.09      ,  46.55      ,
        41.7       ,  48.29      ,   7.09      ,  36.81      ,
        46.98      ,   9.88      ,   4.26      ,  37.31      ,
        29.15      ,   7.85      ,  39.97      ,  10.88      ,
         9.02      ,   9.05      ,  33.59      ,  43.98      ,
        20.23      ,  41.01      ,  22.52      ,  19.47      ,
        23.67      ,  15.77      ,  12.38      ,  45.08      ,
        19.81      , 101.03970354,  45.42      ,  31.59      ,
         6.73      ,  47.05      ,  31.76      ,  17.41      ,
         7.82      ,  39.91      ,  31.38      ,  27.14      ,
        44.8       ,  39.64      ,   8.43      ,  13.18      ,
        37.45      ,   2.64      ,  28.92      ,  38.36      ,
        17.76      ,  41.24      ,  42.48      ,  20.47      ,
         8.35      ,  12.23      ,  36.39      ,  36.28      ,
        32.42      ,  35.        ,  13.34      ,   9.9       ,
        20.64      ,  23.64      ,   8.51      ,  29.73      ,
        25.79      ,  30.96      ,  43.73      , 108.14699381,
        46.2       ,  35.65      ,   8.47      ,  29.24      ,
        30.73      ,  21.78      ,  37.09      ,  46.78      ,
        46.35      ,  23.09      ,   6.55      ,  49.26      ,
        42.11      ,   7.11      ,  43.62      ,  29.97      ,
        20.55      ,   3.68      ,  17.42      ,  40.34      ,
         1.23      ,  20.51      ,  27.33      ,  46.07      ,
        17.97      ,  18.        ,  37.14      ,  23.16      ,
        23.17      ,   7.9       ,   9.64      , 126.5476283 ,
        18.76      ,  29.45      ,   1.64      ,   9.72      ,
        48.09      ,   8.28      ,  49.85      ,  25.61      ,
        30.17      ,   4.29      ,  37.75      ,  11.29      ,
        45.        ,  11.05      ,  10.34      ,   2.79      ,
        24.13      ,  28.68      ,   4.22      ,  39.        ,
        23.21      ,  22.6       ,  28.42      ,   8.61      ,
        43.23      ,  47.36      ,  19.29      ,  21.03      ,
         8.65      ,  36.08      ,  33.29      ,   2.33      ,
        12.32      ,  33.92      ,   1.97      ,   6.1       ,
        40.2       ,   9.75      ,  32.98      ,  12.67      ,
         5.87      ,  12.92      ,  42.93      ,  41.68      ,
        20.46      ,  33.74      ,  11.04      ,  15.36      ,
        44.92      ,   5.19      ,  11.19      ,   9.89      ,
        29.57      ,  21.65      ,  41.05      ,  17.75      ,
        13.71      ,  19.6       ,  29.92      ,  14.14      ,
        31.58      ,  21.06      ,  28.05      ,  22.37      ,
        47.47      ,  38.42      ,   7.87      ,  43.55      ,
        24.88      ,  44.83      ,  40.19      ,  21.84      ,
         2.1       ,  14.17      ,  27.54      ,   7.83      ,
        41.91      ,  49.24      ,  26.76      ,   9.41      ,
        14.34      ,   1.9       ,  45.8       ,   6.77      ,
        14.43      ,  28.15      ,  32.92      ,   1.54      ,
         7.71      ,  45.1       ,  43.82      ,  30.27      ,
        30.43      ,   9.59      ,  45.81      ,  21.52      ,
        19.77      ,  26.43      ,   3.3       ,   9.15      ,
         5.06      ,  13.02      ,  20.08      ,  15.15      ,
        18.43      ,  36.23      ,  15.56      ,  28.75      ,
        24.33      ,  36.9       ,  11.53      ,   2.53      ,
        13.85      ,  30.16      ,  25.32      ,  30.25      ,
        17.38      ,  38.77      ,   6.22      ,   4.68      ,
        25.28      ,  34.73      ,  22.31      ,  13.07      ,
        41.14      ,  35.04      ,  18.69      ,   5.49      ,
        45.95      ,   7.7       ,  47.56      ,  22.85      ])

In [8]:
print(df["Trip_Distance_km"].describe())
print(df["Trip_Distance_km"].isnull().sum())

count    950.000000
mean      27.070547
std       19.905300
min        1.230000
25%       12.632500
50%       25.830000
75%       38.405000
max      146.067047
Name: Trip_Distance_km, dtype: float64
50

In [9]:
df["Trip_Distance_km"].fillna(df["Trip_Distance_km"].median(), inplace=True)

/tmp/ipykernel_166/1199234466.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Trip_Distance_km"].fillna(df["Trip_Distance_km"].median(), inplace=True)

In [10]:
Q1 = df["Trip_Distance_km"].quantile(0.25)
Q3 = df["Trip_Distance_km"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df = df[(df["Trip_Distance_km"] >= lower_bound) &
        (df["Trip_Distance_km"] <= upper_bound)]

In [13]:
df["Time_of_Day"].unique()
df["Time_of_Day"].fillna(df["Time_of_Day"].mode()[0], inplace=True)

/tmp/ipykernel_166/3963757613.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Time_of_Day"].fillna(df["Time_of_Day"].mode()[0], inplace=True)
/tmp/ipykernel_166/3963757613.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Time_of_Day"].fillna(df["Time_of_Day"].mode()[0], inplace=True)

In [17]:
df["Day_of_Week"].unique()
df["Day_of_Week"].fillna(df["Day_of_Week"].mode()[0], inplace=True)

/tmp/ipykernel_166/2404678779.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Day_of_Week"].fillna(df["Day_of_Week"].mode()[0], inplace=True)
/tmp/ipykernel_166/2404678779.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Day_of_Week"].fillna(df["Day_of_Week"].mode()[0], inplace=True)

In [22]:
df["Passenger_Count"].unique()
df["Passenger_Count"].fillna(df["Passenger_Count"].mode()[0], inplace=True)

/tmp/ipykernel_166/556499363.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Passenger_Count"].fillna(df["Passenger_Count"].mode()[0], inplace=True)
/tmp/ipykernel_166/556499363.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Passenger_Count"].fillna(df["Passenger_Count"].mode()[0], inplace=True)

In [25]:
df["Traffic_Conditions"].unique()
df["Traffic_Conditions"].fillna(df["Traffic_Conditions"].mode()[0], inplace=True)

/tmp/ipykernel_166/1063952371.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Traffic_Conditions"].fillna(df["Traffic_Conditions"].mode()[0], inplace=True)
/tmp/ipykernel_166/1063952371.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Traffic_Conditions"].fillna(df["Traffic_Conditions"].mode()[0], inplace=True)

In [26]:
df.isnull().sum()

Trip_Distance_km          0
Time_of_Day               0
Day_of_Week               0
Passenger_Count           0
Traffic_Conditions        0
Weather                  49
Base_Fare                50
Per_Km_Rate              48
Per_Minute_Rate          48
Trip_Duration_Minutes    50
Trip_Price               49
dtype: int64

In [29]:
df["Weather"].unique()
df["Weather"].fillna(df["Weather"].mode()[0],inplace=True)

/tmp/ipykernel_166/644516991.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Weather"].fillna(df["Weather"].mode()[0],inplace=True)
/tmp/ipykernel_166/644516991.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Weather"].fillna(df["Weather"].mode()[0],inplace=True)

In [31]:
df["Base_Fare"].unique()
df["Base_Fare"].fillna(df["Base_Fare"].median(),inplace=True)

/tmp/ipykernel_166/3234336437.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Base_Fare"].fillna(df["Base_Fare"].median(),inplace=True)
/tmp/ipykernel_166/3234336437.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Base_Fare"].fillna(df["Base_Fare"].median(),inplace=True)

In [33]:
df["Per_Km_Rate"].unique()
df["Per_Km_Rate"].fillna(df["Per_Km_Rate"].median(),inplace=True)

/tmp/ipykernel_166/449809544.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Per_Km_Rate"].fillna(df["Per_Km_Rate"].median(),inplace=True)
/tmp/ipykernel_166/449809544.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Per_Km_Rate"].fillna(df["Per_Km_Rate"].median(),inplace=True)

In [35]:
df["Per_Minute_Rate"].unique()
df["Per_Minute_Rate"].fillna(df["Per_Minute_Rate"].median(),inplace=True)

/tmp/ipykernel_166/2386332101.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Per_Minute_Rate"].fillna(df["Per_Minute_Rate"].median(),inplace=True)
/tmp/ipykernel_166/2386332101.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Per_Minute_Rate"].fillna(df["Per_Minute_Rate"].median(),inplace=True)

In [36]:
df.isnull().sum()

Trip_Distance_km          0
Time_of_Day               0
Day_of_Week               0
Passenger_Count           0
Traffic_Conditions        0
Weather                   0
Base_Fare                 0
Per_Km_Rate               0
Per_Minute_Rate           0
Trip_Duration_Minutes    50
Trip_Price               49
dtype: int64

In [38]:
df["Trip_Duration_Minutes"].unique()
df["Trip_Duration_Minutes"].fillna(df["Trip_Duration_Minutes"].median(),inplace=True)

/tmp/ipykernel_166/3762728412.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Trip_Duration_Minutes"].fillna(df["Trip_Duration_Minutes"].median(),inplace=True)
/tmp/ipykernel_166/3762728412.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Trip_Duration_Minutes"].fillna(df["Trip_Duration_Minutes"].median(),inplace=True)

In [39]:
df.isnull().sum()

Trip_Distance_km          0
Time_of_Day               0
Day_of_Week               0
Passenger_Count           0
Traffic_Conditions        0
Weather                   0
Base_Fare                 0
Per_Km_Rate               0
Per_Minute_Rate           0
Trip_Duration_Minutes     0
Trip_Price               49
dtype: int64

In [41]:
df["Trip_Price"].unique()
df["Trip_Price"].fillna(df["Trip_Price"].median(),inplace = True)

/tmp/ipykernel_166/4252208017.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Trip_Price"].fillna(df["Trip_Price"].median(),inplace = True)
/tmp/ipykernel_166/4252208017.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Trip_Price"].fillna(df["Trip_Price"].median(),inplace = True)

In [42]:
df.isnull().sum()

Trip_Distance_km         0
Time_of_Day              0
Day_of_Week              0
Passenger_Count          0
Traffic_Conditions       0
Weather                  0
Base_Fare                0
Per_Km_Rate              0
Per_Minute_Rate          0
Trip_Duration_Minutes    0
Trip_Price               0
dtype: int64

In [43]:
df

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.560,0.80,0.32,53.82,36.2624
1,47.59,Afternoon,Weekday,1.0,High,Clear,3.515,0.62,0.43,40.57,48.8350
2,36.87,Evening,Weekend,1.0,High,Clear,2.700,1.21,0.15,37.27,52.9032
3,30.33,Evening,Weekday,4.0,Low,Clear,3.480,0.51,0.15,116.81,36.4698
4,25.83,Evening,Weekday,3.0,High,Clear,2.930,0.63,0.32,22.64,15.6180
...,...,...,...,...,...,...,...,...,...,...,...
995,5.49,Afternoon,Weekend,4.0,Medium,Clear,2.390,0.62,0.49,58.39,34.4049
996,45.95,Night,Weekday,4.0,Medium,Clear,3.120,0.61,0.29,61.96,62.1295
997,7.70,Morning,Weekday,3.0,Low,Rain,2.080,1.78,0.29,54.18,33.1236
998,47.56,Morning,Weekday,1.0,Low,Clear,2.670,0.82,0.17,114.94,61.2090
999,22.85,Morning,Weekend,3.0,Medium,Clear,4.340,1.22,0.23,29.69,45.4437

In [44]:
df.describe()

,Trip_Distance_km,Passenger_Count,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
count,980.000000,980.000000,980.000000,980.000000,980.000000,980.000000,980.000000
mean,25.097347,2.511224,3.504020,1.231296,0.293153,62.063133,52.014227
std,14.012551,1.079513,0.846955,0.418620,0.112966,31.439730,23.491779
min,1.230000,1.000000,2.010000,0.500000,0.100000,5.010000,6.126900
25%,12.880000,2.000000,2.770000,0.877500,0.190000,36.815000,34.397775
50%,25.830000,3.000000,3.515000,1.220000,0.290000,61.945000,48.835000
75%,37.037500,3.000000,4.200000,1.572500,0.390000,87.742500,65.987100
max,49.990000,4.000000,5.000000,2.000000,0.500000,119.840000,138.642500

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 980 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Trip_Distance_km       980 non-null    float64
 1   Time_of_Day            980 non-null    object
 2   Day_of_Week            980 non-null    object
 3   Passenger_Count        980 non-null    float64
 4   Traffic_Conditions     980 non-null    object
 5   Weather                980 non-null    object
 6   Base_Fare              980 non-null    float64
 7   Per_Km_Rate            980 non-null    float64
 8   Per_Minute_Rate        980 non-null    float64
 9   Trip_Duration_Minutes  980 non-null    float64
 10  Trip_Price             980 non-null    float64
dtypes: float64(7), object(4)
memory usage: 91.9+ KB

In [58]:
from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()
df["Time_of_Day"]=Le.fit_transform(df["Time_of_Day"])
df["Time_of_Day"]=df["Time_of_Day"].astype(float)
df

/tmp/ipykernel_166/817331886.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Time_of_Day"]=Le.fit_transform(df["Time_of_Day"])
/tmp/ipykernel_166/817331886.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Time_of_Day"]=df["Time_of_Day"].astype(float)

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,2.0,0,3.0,1,0.0,3.560,0.80,0.32,53.82,36.2624
1,47.59,0.0,0,1.0,0,0.0,3.515,0.62,0.43,40.57,48.8350
2,36.87,1.0,1,1.0,0,0.0,2.700,1.21,0.15,37.27,52.9032
3,30.33,1.0,0,4.0,1,0.0,3.480,0.51,0.15,116.81,36.4698
4,25.83,1.0,0,3.0,0,0.0,2.930,0.63,0.32,22.64,15.6180
...,...,...,...,...,...,...,...,...,...,...,...
995,5.49,0.0,1,4.0,2,0.0,2.390,0.62,0.49,58.39,34.4049
996,45.95,3.0,0,4.0,2,0.0,3.120,0.61,0.29,61.96,62.1295
997,7.70,2.0,0,3.0,1,1.0,2.080,1.78,0.29,54.18,33.1236
998,47.56,2.0,0,1.0,1,0.0,2.670,0.82,0.17,114.94,61.2090
999,22.85,2.0,1,3.0,2,0.0,4.340,1.22,0.23,29.69,45.4437

In [63]:
df["Day_of_Week"]=Le.fit_transform(df["Day_of_Week"])
df["Day_of_Week"]=df["Day_of_Week"].astype(float)
df

/tmp/ipykernel_166/3510503890.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Day_of_Week"]=Le.fit_transform(df["Day_of_Week"])
/tmp/ipykernel_166/3510503890.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Day_of_Week"]=df["Day_of_Week"].astype(float)

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,2.0,0.0,3.0,1.0,0.0,3.560,0.80,0.32,53.82,36.2624
1,47.59,0.0,0.0,1.0,0.0,0.0,3.515,0.62,0.43,40.57,48.8350
2,36.87,1.0,1.0,1.0,0.0,0.0,2.700,1.21,0.15,37.27,52.9032
3,30.33,1.0,0.0,4.0,1.0,0.0,3.480,0.51,0.15,116.81,36.4698
4,25.83,1.0,0.0,3.0,0.0,0.0,2.930,0.63,0.32,22.64,15.6180
...,...,...,...,...,...,...,...,...,...,...,...
995,5.49,0.0,1.0,4.0,2.0,0.0,2.390,0.62,0.49,58.39,34.4049
996,45.95,3.0,0.0,4.0,2.0,0.0,3.120,0.61,0.29,61.96,62.1295
997,7.70,2.0,0.0,3.0,1.0,1.0,2.080,1.78,0.29,54.18,33.1236
998,47.56,2.0,0.0,1.0,1.0,0.0,2.670,0.82,0.17,114.94,61.2090
999,22.85,2.0,1.0,3.0,2.0,0.0,4.340,1.22,0.23,29.69,45.4437

In [59]:
df['Traffic_Conditions']=Le.fit_transform(df["Traffic_Conditions"])
df["Traffic_Conditions"]=df["Traffic_Conditions"].astype(float)
df

/tmp/ipykernel_166/3892174643.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Traffic_Conditions']=Le.fit_transform(df["Traffic_Conditions"])
/tmp/ipykernel_166/3892174643.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Traffic_Conditions"]=df["Traffic_Conditions"].astype(float)

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,2.0,0,3.0,1.0,0.0,3.560,0.80,0.32,53.82,36.2624
1,47.59,0.0,0,1.0,0.0,0.0,3.515,0.62,0.43,40.57,48.8350
2,36.87,1.0,1,1.0,0.0,0.0,2.700,1.21,0.15,37.27,52.9032
3,30.33,1.0,0,4.0,1.0,0.0,3.480,0.51,0.15,116.81,36.4698
4,25.83,1.0,0,3.0,0.0,0.0,2.930,0.63,0.32,22.64,15.6180
...,...,...,...,...,...,...,...,...,...,...,...
995,5.49,0.0,1,4.0,2.0,0.0,2.390,0.62,0.49,58.39,34.4049
996,45.95,3.0,0,4.0,2.0,0.0,3.120,0.61,0.29,61.96,62.1295
997,7.70,2.0,0,3.0,1.0,1.0,2.080,1.78,0.29,54.18,33.1236
998,47.56,2.0,0,1.0,1.0,0.0,2.670,0.82,0.17,114.94,61.2090
999,22.85,2.0,1,3.0,2.0,0.0,4.340,1.22,0.23,29.69,45.4437

In [56]:
df["Weather"]=Le.fit_transform(df["Weather"])
df["Weather"]=df["Weather"].astype(float)
df

/tmp/ipykernel_166/222475234.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Weather"]=Le.fit_transform(df["Weather"])
/tmp/ipykernel_166/222475234.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Weather"]=df["Weather"].astype(float)

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,2,0,3.0,1,0.0,3.560,0.80,0.32,53.82,36.2624
1,47.59,0,0,1.0,0,0.0,3.515,0.62,0.43,40.57,48.8350
2,36.87,1,1,1.0,0,0.0,2.700,1.21,0.15,37.27,52.9032
3,30.33,1,0,4.0,1,0.0,3.480,0.51,0.15,116.81,36.4698
4,25.83,1,0,3.0,0,0.0,2.930,0.63,0.32,22.64,15.6180
...,...,...,...,...,...,...,...,...,...,...,...
995,5.49,0,1,4.0,2,0.0,2.390,0.62,0.49,58.39,34.4049
996,45.95,3,0,4.0,2,0.0,3.120,0.61,0.29,61.96,62.1295
997,7.70,2,0,3.0,1,1.0,2.080,1.78,0.29,54.18,33.1236
998,47.56,2,0,1.0,1,0.0,2.670,0.82,0.17,114.94,61.2090
999,22.85,2,1,3.0,2,0.0,4.340,1.22,0.23,29.69,45.4437

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 980 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Trip_Distance_km       980 non-null    float64
 1   Time_of_Day            980 non-null    float64
 2   Day_of_Week            980 non-null    float64
 3   Passenger_Count        980 non-null    float64
 4   Traffic_Conditions     980 non-null    float64
 5   Weather                980 non-null    float64
 6   Base_Fare              980 non-null    float64
 7   Per_Km_Rate            980 non-null    float64
 8   Per_Minute_Rate        980 non-null    float64
 9   Trip_Duration_Minutes  980 non-null    float64
 10  Trip_Price             980 non-null    float64
dtypes: float64(11)
memory usage: 91.9 KB

In [65]:
X= df.drop('Trip_Price', axis=1)
y=df["Trip_Price"]

In [66]:
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y,test_size=0.3,random_state=42)

In [67]:
model = LinearRegression()
model.fit(Xtrain,ytrain)

LinearRegression()

In [68]:
print("Intercept : ",model.intercept_)
print("Slope:",model.coef_)

Intercept :  -42.75146257857914
Slope: [ 1.14631479 -0.3797153   0.7487446   0.72707582 -0.65501495  0.659903
  0.76723346 24.23477977 55.49784648  0.25876666]

MODEL EVALUATION

In [69]:
ypred = model.predict(Xtest)
ypred

array([ 70.82783896,  50.17588491,  28.07969164,  18.23051205,
        63.91975169,  25.76790595,  57.93160219,  32.70191764,
        43.73237366,  59.59161326,  35.32962438,  65.6840562 ,
        27.39989857,  60.67533267,  56.56624354,  60.8409055 ,
        24.1388914 ,  49.53231255,  35.39366829,  61.4540681 ,
        62.66008927,  88.39138565,  91.37256684,  92.28828049,
        39.59732189,  63.75567826, -12.0325959 ,  80.13505322,
        61.62282508,  39.6032719 ,  32.96228964,  38.70561724,
        55.15398536,  65.26149098,  63.64445322,  44.04323686,
        53.2278527 ,  20.36273133,  83.01736366,  82.6431068 ,
        17.96324995,  50.98396228,  67.4398943 ,  57.3845613 ,
        92.27043891,  31.20862436,  32.22590482,  51.65713011,
        77.69850602,  41.2426458 ,  39.90023072,  69.05371466,
        59.76668525,  33.16518161,  79.84192347,  48.75379429,
        45.2768467 ,  51.03660361,  38.82426147,  47.23321027,
        34.82236161,  59.70269561,  44.59563364,  90.25043449,
        65.81929567,  24.59533663,  42.95904549,  83.5344542 ,
        59.08140168,  53.14849274,  50.83873408,  62.4211025 ,
        12.50619156,  51.41016749,  33.99432346,  62.58349351,
        58.79924935,  44.16266885,   0.6428015 ,  59.54676351,
        53.78042666,  50.02696876,  66.47941185,  48.25629461,
        70.30151618,  73.36788618,  52.09210548,  63.8563998 ,
        50.46020621,  66.27408474,  77.23055351,  24.13188894,
        72.44985416,  23.61484715,  64.20093538,  66.67569476,
        54.80651453,  45.880519  ,  33.08380898,  33.39113043,
        10.71050634,  55.78452048,  23.96691703,  53.61102033,
        53.66118536,  46.87162958,  25.05140527,  73.34609743,
        38.67893099,  69.06299645,  57.98128878,  45.58320642,
        54.06248154,  24.73976843,  54.51851869,  41.18510072,
        35.07313746,  69.90722607,  47.56183437,  60.95333001,
        25.01712713,  30.94369574,  28.47297705,  21.58003043,
        54.94612482,  79.72331005,  85.68116904,  41.95441649,
        54.45199413,  36.48048463,  72.84739211,  45.36247832,
        75.59858289,   1.01091711,  52.89952815,  59.93098254,
        57.74467568,  81.89886194,  34.05991383,  36.50714388,
        42.88359309,  42.37034507,  83.2505687 ,  42.99035987,
        56.56616541,  95.9837403 ,  50.02198319,  44.44112649,
        19.48634563,  44.57438488,  61.15323897,  57.04205197,
        28.58915399,  70.30710169,  54.90247024,  30.91535827,
        30.6695723 ,  43.85831472,  74.50551215,   3.190488  ,
        49.52152735,  32.78212077,  92.43434289,  97.07238044,
        15.00795581,  65.23365744,  75.25115375,  29.32302703,
        67.12400574,  81.34769115,  24.22494994,  59.31101507,
        83.20289932,  60.59040659,  59.08528331,  25.64961342,
        21.41150936,  55.15355244,  30.12447332,  34.29158755,
        75.40483139,  54.92051574,  91.32860155,  17.97841271,
        10.65983929,  11.73575641,  65.88848683,  36.75633589,
        82.07497769,  55.33563664,   9.19048861,  43.26077788,
        74.06680648,  43.95877343,  56.40307942,  45.284654  ,
        42.89599684,  56.2876375 ,  67.63920505,  29.7441871 ,
        58.99343059,  70.31641766,  41.59336852,  83.17216581,
        20.59322501,  54.17969274,  25.3970845 ,  58.06694881,
        80.72537792,   8.55836389,  33.08481292,  51.12556081,
        82.16631383,  55.60046284,  27.63592948,  44.86131644,
        67.7679007 ,  71.94914828,  19.88261682,  76.28050953,
        53.63920788,  18.10840922,  49.97379323,  72.03740482,
        24.52855708,  39.27173668,  43.25580598,  82.04378595,
        72.46561609,  61.19807464,   8.81187703,  52.53546236,
        70.52809515,  63.9979171 ,   5.81490508,  29.60647158,
        50.52780473,  39.10210368,  66.48090682,  63.90810231,
        41.70081297,  33.40962853,   1.41078861,  54.32011796,
        20.98489842,  48.3419901 ,  34.92922664,  75.95367024,
        34.72006213,  58.96862305,  52.36331589,  52.78387409,
        68.10676074,  86.80814063,  26.77146716,  49.76427596,
        86.0689724 ,  71.18086822,  76.61454381,  52.65454304,
        27.88640501,  75.61057619,  56.37418378,  71.66212517,
        52.98731408,  33.43927801,  36.20254942,  62.35026091,
        82.2000817 ,  21.0458102 ,  40.36828471,  25.94659329,
        29.95475751,  51.70979422,  28.27223136,  53.18963771,
        20.72195045,  44.22448532,  11.57741665,  72.44605944,
        11.74198838,  81.83576989,  85.3312209 ,  56.89280928,
        41.1586931 ,  40.422911  ,  53.87397533,  23.50003069,
        70.44455366,  68.53715297,  48.8186263 ,  62.41266218,
        53.82805058,  33.10563065])

In [70]:
print("metrics : ")
r2 = r2_score(ytest,ypred)
print("R2 : ",r2)
N = df.shape[0]
P=df.shape[1]
adj_r2 = 1-(((1-r2**2)*(N-1))/(N-P-1))
print("Adjusted R2 : ",adj_r2)
print("MSE : ",mean_squared_error(ytest,ypred))
print("MAE : ",mean_absolute_error(ytest,ypred))

metrics :
R2 :  0.8368640215128662
Adjusted R2 :  0.6969361790311266
MSE :  89.57001578923642
MAE :  7.100549363951659

In [71]:
print("Training eff :", model.score(Xtrain,ytrain))
print("Testing eff :", model.score(Xtest,ytest))

Training eff : 0.8153857460657165
Testing eff : 0.8368640215128662

In [72]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
Xtrain = scalar.fit_transform(Xtrain)
Xtest = scalar.transform(Xtest) # to avoid data leakage to model because model can learn from tarining data buty not from test data

In [77]:
new_data = df.iloc[4:5,:-1]
pred = model.predict(new_data)[0]
print("Predicted value : ",pred*100000)

Predicted value :  2979305.402738808

In [76]:
df

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,2.0,0.0,3.0,1.0,0.0,3.560,0.80,0.32,53.82,36.2624
1,47.59,0.0,0.0,1.0,0.0,0.0,3.515,0.62,0.43,40.57,48.8350
2,36.87,1.0,1.0,1.0,0.0,0.0,2.700,1.21,0.15,37.27,52.9032
3,30.33,1.0,0.0,4.0,1.0,0.0,3.480,0.51,0.15,116.81,36.4698
4,25.83,1.0,0.0,3.0,0.0,0.0,2.930,0.63,0.32,22.64,15.6180
...,...,...,...,...,...,...,...,...,...,...,...
995,5.49,0.0,1.0,4.0,2.0,0.0,2.390,0.62,0.49,58.39,34.4049
996,45.95,3.0,0.0,4.0,2.0,0.0,3.120,0.61,0.29,61.96,62.1295
997,7.70,2.0,0.0,3.0,1.0,1.0,2.080,1.78,0.29,54.18,33.1236
998,47.56,2.0,0.0,1.0,1.0,0.0,2.670,0.82,0.17,114.94,61.2090
999,22.85,2.0,1.0,3.0,2.0,0.0,4.340,1.22,0.23,29.69,45.4437